### ISSUE TITLE
Search returns no results, documents not being added to index.

### ISSUE THREAD

**Issue by poncianodiego** [babenkoivan/scout-elasticsearch-driver#100]
Hello there, first of thanks for this nice package.

I have followed all the instructions and when I run `php artisan elastic:create-index "App\IndexConfigurators\ProductIndexConfigurator"` index is created just fine.

When I run `php artisan scout:import "App\Product"` is tells me:

Please help!

**Comment by poncianodiego** [comment]
Never mind! I am an idiot, I'm running queues just had to run them lol

**Comment by babenkoivan** [comment]
I have to create some troubleshooting page, this is a common mistake :)
I'm closing the issue, because it's already solved.
