### ISSUE TITLE
elastic search by joining multiple models ?

### ISSUE THREAD

**Issue by imtarundhiman** [babenkoivan/scout-elasticsearch-driver#118]
Is there any way to search from multiple tables (joins) ??

**Comment by babenkoivan** [comment]
Hi @imtarundhiman, no, now it's not possible

**Comment by iget-esoares** [comment]
Elastic search is not good doing relational things, although it's possible.

I thin that's not something that this package can/should work for, since it's a very specific situation.

I'll close this issue for clean up reasons.

**Comment by vahidalvandi** [comment]
i have eshop with huge product ,each product join to attribute table then search contain result from two table , how i elastic search can work whit this purpose ??

thank you

**Comment by babenkoivan** [comment]
@vahidalvandi you may consider using [`toSearchableArray` method](https://laravel.com/docs/5.8/scout#configuring-searchable-data) in your model to add attributes from two relational tables.
