### ISSUE TITLE
Not working on Scout 5.0.3

### ISSUE THREAD

**Issue by BlazingRockStorm** [babenkoivan/scout-elasticsearch-driver#119]
I have to downgrade the version of Scout to 4.0.x to install this driver

**Comment by orukaz** [comment]
It would be super if it works with Laravel Scout 5.x ;) How different are Scout 4.x and 5.x ?

**Comment by BlazingRockStorm** [comment]
![image](https://user-images.githubusercontent.com/22587774/44082432-68e93c3e-9fdb-11e8-8ec5-998902532c12.png)
@orukaz I don't know. When I run the command, it returned this

**Comment by babenkoivan** [comment]
Hey guys, currently I'm working on a new version v4.0.0, that will be compatible with Scout 5.0.

**Comment by bavial** [comment]
> Hey guys, currently I'm working on a new version v4.0.0, that will be compatible with Scout 5.0.

Hi @babenkoivan. There are already Scout 6 versions. Planning to do support for this? Thnks

**Comment by babenkoivan** [comment]
Scout 6 is now supported.
