### ISSUE TITLE
Index prefix?

### ISSUE THREAD

**Issue by orukaz** [babenkoivan/scout-elasticsearch-driver#123]
Is it possible to configure **index prefix**?

If this feature does not exist, could it be added? It is very useful feature and simplifies and keeps clean  index configuration for Laravel projects/apps that are using the same Elastic Search environment (no need to install new Elastic Search environment for every project).

Index prefix would keep every Laravel projects/apps indexes unique for same ElasticSearch environment.

Index configuration class (no need to change, it is fine): 

```
<?php

namespace App;

use ScoutElastic\IndexConfigurator;

class MyIndexConfigurator extends IndexConfigurator
{
    // It's not obligatory to determine name. By default it'll be a snaked class name without IndexConfigurator part.
    protected $name = 'my_index'; 

...
```

Config file (new param "index_prefix" added):

```
<?php
return [
    'client' => [
        'hosts' => [
            env('SCOUT_ELASTIC_HOST', 'localhost:9200')
        ]
    ],
    'update_mapping' => env('SCOUT_ELASTIC_UPDATE_MAPPING', true),
    'indexer' => env('SCOUT_ELASTIC_INDEXER', 'single'),
    'document_refresh' => env('SCOUT_ELASTIC_DOCUMENT_REFRESH'),
    'index_prefix' => env('SCOUT_ELASTIC_INDEX_PREFIX', 'myproject_')
];
```

If the "index_prefix" is defined, for example with **"myproject_"**, then all the indexes will be changed like that **"myproject_my_index"**.

I really hope you can add this config parameter ;)

**Comment by babenkoivan** [comment]
Hi @orukaz, actually you can configure it in `scout.php`file, the `prefix` option does the job.
