### ISSUE TITLE
Missing404Exception on creation of new records

### ISSUE THREAD

**Issue by craigward** [babenkoivan/scout-elasticsearch-driver#124]
Hi, 

I have an app which is using this package. I'm not overly familiar with Elastic Search so it could be my understanding, rather than a bug/error.

I get the below error when creating a new record. 
```
Missing404Exception

{"_index":"instance_index","_type":"instances","_id":"545","_version":1,"result":"not_found","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":458,"_primary_term":9}
```

The `_id` of 545 is the new record, and it seem like the driver is trying to delete the record, before creating the new one? but then can't as the record exists.

Why would I be getting this error?

**Comment by craigward** [comment]
It looks like my problem is the same as this issue #88 

The creation of a new record doesn't get put into the index until a 'publish' flag has been set. Is there a way to solve this?

**Comment by babenkoivan** [comment]
Hi @craigward, unfortunately there is no workaround for `shouldBeSearchable` flag at the moment. I'll try to solve it in v4 by adding additional query, checking that the model exists in the index, before trying to delete it. 

For now, you can silence the error as described in https://github.com/babenkoivan/scout-elasticsearch-driver/issues/88.
