### ISSUE TITLE
Can whereIn be used to filter data during search?

### ISSUE THREAD

**Issue by zhiyong80** [babenkoivan/scout-elasticsearch-driver#133]
Something like
```
App\MyModel::search('phone')::search('phone')
->whereIn('brand', ['apple', 'samsung'])
->get();
```
Or we need to retrieve all results without whereIn then manually filter data after search?

**Comment by babenkoivan** [comment]
Hi @zhiyong80, yes, you can use `whereIn` method as described [here](https://github.com/babenkoivan/scout-elasticsearch-driver#available-filters).

**Comment by zhiyong80** [comment]
@babenkoivan sorry I missed that part of doc. Please close the issue.
