### ISSUE TITLE
Result order

### ISSUE THREAD

**Issue by ametad** [babenkoivan/scout-elasticsearch-driver#14]
Can the order of the result be set somewhere?

Normally I would put it with the request to Elasticsearch, as described here: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-request-sort.html

**Comment by ametad** [comment]
Did not find it in the README, but found in the code itself 👍 

https://github.com/babenkoivan/scout-elasticsearch-driver/blob/f29e531ad7942c15c22752d68f405b4058be586c/src/Builders/FilterBuilder.php#L115

**Comment by calvera** [comment]
hello, is it possible add *special* elastic sort?
i need something like
```json
{
  "track_scores": true,
  "sort" : [
        {
            "_geo_distance" : {
                "location" : {
                    "lat" : 50.0755381,
                    "lon" : 14.4378005
                },
                "order" : "asc",
                "unit" : "km"
            }
        }
    ],
  "query": {
    "multi_match": {
      "query": "svetly",
      "fields": [
                        "name.czech_lowercase^2",
                        "name.czech_hunspell",
                        "description^0.3"
        
        ]
    }
  },
  "highlight": {
    "fields": {
      "name.czech_hunspell": {"type":"plain"},
      "name.czech_lowercase": {"type":"plain"},
      "description": {"type":"plain"}
    }
  }
}
```

thanks!

**Comment by babenkoivan** [comment]
Hi @calvera, it's possible only with `searchRaw` method.

**Comment by calvera** [comment]
thanks, i like #98 and i will use it
