### ISSUE TITLE
Multi-tenant restful

### ISSUE THREAD

**Issue by yashiroiori** [babenkoivan/scout-elasticsearch-driver#140]
Finally config Laravel 5.6 to use https://laravel-tenancy.com in restful with Angular 6.
Before restful work using this package to create an index per model, but with this change I have to create a model index with prefix or sufix with the slug to identify the index per account because multiples accounts can use the same app, how do set index name of each model to the account request??
Backend make the creation, update and delete data for models and frontend [angular 6] searxh directly in elasticsearch.
Or any suggestions to make better that work??

Sorry for my bad english.

**Comment by babenkoivan** [comment]
Hi @yashiroiori, I'm not sure, that I understood your problem correctly, but if you need the same index for different models, you can override method `getIndexConfigurator` in each model to return the same `indexConfigurator` object.

**Comment by yashiroiori** [comment]
Resolve set name like this:
```php
public function getName() {
        return strtolower(str_replace('prefix_','',app(\Hyn\Tenancy\Environment::class)->tenant()->uuid)).'_model_name';
}
```
