### ISSUE TITLE
BUG when there is a lot of records

### ISSUE THREAD

**Issue by LonnyX** [babenkoivan/scout-elasticsearch-driver#149]
Hello,

I have a table with 100K records (indexed osht ES) but when I try to search something that give me more than 10k results I have this error:

> **Elasticsearch\Common\Exceptions\ServerErrorResponseException**
> {"error":{"root_cause":[{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [16650]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"default","node":"SyUlqHsCRT2yZ2JtqNOo_Q","reason":{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [16650]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}}]},"status":500}

I tried to add a limit with `take()` but it doesn't works if `paginate()` is used after.

Here is a SO topic about this: https://stackoverflow.com/questions/35206409/elasticsearch-2-1-result-window-is-too-large-index-max-result-window/35223055#35223055

I think increasing the `max_result_window` is not a solution

**Comment by babenkoivan** [comment]
Hi @LonnyX, usually [Scroll API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html) is used in such cases. But it's not supported by the package. My recommendation in your case is to make a more specific search query or to increase `max_result_window`.

**Comment by LonnyX** [comment]
When you have a lot of records, even I make specific search (I can't control what visitors search) it'll return more than 10K records.

For now I fixed this by increasing the `max_result_window` but maybe after, it'll be good to use to Scroll API? :) 

Thanx
