### ISSUE TITLE
Installation request for laravel/scout == 6.0.0.0 -> satisfiable by laravel/scout[v6.0.0].

### ISSUE THREAD

**Issue by simonproud** [babenkoivan/scout-elasticsearch-driver#155]
Problem 1
    - Installation request for laravel/scout == 6.0.0.0 -> satisfiable by laravel/scout[v6.0.0].
    - asolopovas/scout-elasticsearch v3.0.0 requires laravel/scout ^3.0 -> satisfiable by laravel/scout[3.0.x-dev].
    - asolopovas/scout-elasticsearch v3.0.1 requires laravel/scout ^3.0 -> satisfiable by laravel/scout[3.0.x-dev].
    - Conclusion: don't install laravel/scout 3.0.x-dev
    - Installation request for asolopovas/scout-elasticsearch ^3.0 -> satisfiable by asolopovas/scout-elasticsearch[v3.0.0, v3.0.1].

**Comment by loic-lopez** [comment]
This project is cool but need to be upgraded to scout v6.

**Comment by babenkoivan** [comment]
Added Scout v6 support in `v3.9.0`. Please, update the package in your projects.
