### ISSUE TITLE
Model::search()->get() return empty response with laravel Horizon and scout queues enabled

### ISSUE THREAD

**Issue by loic-lopez** [babenkoivan/scout-elasticsearch-driver#157]
I followed step by step the readme, create the index, migrate the index, configure a mapping and `User::search()->get()` returns an empty array.

***Obviously my database is migrated and populated.***

**I would like to search a user by:**

- His ***first_name***
- His ***last_name***
- His ***nick_name***

So i have created an **IndexConfigurator**:

    class UserIndexConfigurator extends IndexConfigurator
    {
       use Migratable;

       protected $name = 'user_index';

       /**
       * @var array
       */
       protected $settings = [
        //
       ];
    }

Created a **SearchRule**:

    class UserSearchRule extends SearchRule
    {
        public function buildQueryPayload()
        {
          $query = $this->builder->query;

          return [
              'should' => [
                  [
                      'match' => [
                          'first_name' => [
                              'query' => $query
                          ]
                      ]
                  ],
                  [
                      'match' => [
                          'last_name' => [
                              'query' => $query
                          ]
                      ]
                  ],
                  [
                      'match' => [
                          'nick_name' => [
                              'query' => $query
                          ]
                      ]
                  ]
              ]
          ];
       }
    }

Configured my **User Model** accordingly:

    class User extends Authenticatable
    {
       use Searchable;

       /**
       * @var string
       */
       protected $indexConfigurator = UserIndexConfigurator::class;

       /**
       * @var array
       */
       protected $searchRules = [
           UserSearchRule::class
       ];

       /**
       * @var array
       */
       protected $mapping = [
          'properties' => [
              'first_name' => [
                  'type' => 'text'
              ],
              'last_name' => [
                  'type' => 'text'
              ],
              'nick_name' => [
                  'type' => 'text'
              ],
          ]
      ];
      
       /**
       * The attributes that are mass assignable.
       *
       * @var array
       */
       protected $fillable = [
          'id',
          'first_name',
          'last_name',
          'nick_name',
       ];
    }

Do i missed something?

  [1]: https://github.com/babenkoivan/scout-elasticsearch-driver

**Comment by babenkoivan** [comment]
Hi @loic-lopez, have you fixed an issue?
If not, you can check if you have data in ES by connecting to it using Kibana or receiving data using [get API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html) or [search API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search.html). If data is there, but you can't receive it using `search` method, then check if `soft_deletes` are enabled, try to turn it off.

**Comment by loic-lopez** [comment]
I found the issue:

In the unit tests when scout : ` 'queue' => true`, the user was not pushed to elasticsearch.

So as a fix, what i've done:

**UserSearchTest.php**:
```
 /**
 *
 */
 protected function setUp()
   {
        parent::setUp();
        $this->user = factory(User::class)->make();
        $this->user->nick_name = $this->faker->company;
        $user = User::create($this->user->toArray());
        $user->searchable();
   }
```

**app/config/scout.php**:
```
if (! function_exists('runningUnitTests')) {
    function runningUnitTests() {
        return env('APP_ENV') === 'testing';
    }
}

 /*
|--------------------------------------------------------------------------
| Queue Data Syncing
|--------------------------------------------------------------------------
|
| This option allows you to control if the operations that sync your data
| with your search engines are queued. When this is set to "true" then
| all automatic data syncing will get queued for better performance.
|
*/

'queue' => env('SCOUT_QUEUE', !runningUnitTests()), // bug with queue enabled
```
