### ISSUE TITLE
Missing404Exception Exception

### ISSUE THREAD

**Issue by mauxtin** [babenkoivan/scout-elasticsearch-driver#159]
Sometimes, when a change is saved on a model I get this error message

```
Elasticsearch\Common\Exceptions\Missing404Exception: {"_index":"products","_type":"products","_id":"420156","_version":1,"result":"not_found","_shards":{"total":2,"
```

Any ideas what might cause that?

**Comment by babenkoivan** [comment]
Hi @mauxtin, if you are using `soft_delete`, it can be related to https://github.com/babenkoivan/scout-elasticsearch-driver/issues/88.

**Comment by mauxtin** [comment]
It seems like that was the problem. Please consider adding this to the repo (to avoid having a fork just for this).
