### ISSUE TITLE
No records in search after import

### ISSUE THREAD

**Issue by alvibd** [babenkoivan/scout-elasticsearch-driver#160]
hi,
I am running scout:import command and it shows it's running successfully and completed. however, I cannot find any data stored in my index. here are my codes,
```
protected $mapping = [
        'properties' => [
            'name' => ['type' => 'text'],
            'name_bn' => ['type' => 'text'],
            'address' => ['type' => 'text'],
            'address_bn' => ['type' => 'text'],
            'description' => ['type' => 'text'],
            'description_bn' => ['type' => 'text'],
            'tags' => ['type' => 'keyword'],
            'tags_bn' => ['type' => 'keyword'],
            'category' => ['type' => 'text'],
            'category_bn' => ['type' => 'text'],
            'sub_category' => ['type' => 'text'],
            'sub_category_bn' => ['type' => 'text'],
            'avg_rating' => ['type' => 'float'],
            'area_name' => ['type' => 'text'],
            'location' => ['type' => 'geo_point']
        ]
    ];
```
 and 
```
public function toSearchableArray()
    {
        $array = [
            'name' => $this->name,
            'name_bn' => $this->name_bn,
            'address' => $this->address,
            'address_bn' => $this->address_bn,
            'description' => $this->description,
            'description_bn' => $this->description_bn,
            'tags' => $this->tags()->pluck('name')->all(),
            'tags_bn' => $this->tags()->pluck('name_bn')->all(),
            'category' => $this->category()->first()->name,
            'category_bn' => $this->category()->first()->name_bn,
            'sub_category' => $this->subCategory()->first()->name,
            'sub_category_bn' => $this->subCategory()->first()->name_bn,
            'avg_rating' => $this->avg_rating,
            'area_name' => $this->area_name,
            'location' => [$this->latitude, $this->longitude]
        ];

        return $array;
    }
```

can any one tell me what am I doing wrong here??

**Comment by jlstandout** [comment]
Maybe it's related with issue what I have? 
I have index UserIndexConfigurator
```
<?php
namespace App\Searchable;
use ScoutElastic\IndexConfigurator;
use ScoutElastic\Migratable;
class UserIndexConfigurator extends IndexConfigurator
{
    use Migratable;
    protected $name = 'users';
    /**
     * @var array
     */
    protected $settings = [
        //
    ];
}
```
And index is prefixed with `SCOUT_PREFIX=dev_dev_`.
And then i tried to seed 100 users. I also didn't have any results, when i tried to check users, but then i noticed, that users where added to `dev_dev_users_write` index with type `dev_dev_users`, but when i try to search them, they are searched in index `dev_dev_users`. 
Can someone explain me why sometimes items are postfixed with `_write` and sometimes not? 

**alvibd** I would recommend you to inspect your query and check if index matches with real document index.

You can check document index with GET request `localhost:9200/_search`.

**Comment by alvibd** [comment]
Hello @jlstandout ,

While I cannot certainly say yet before checking tomorrow, but I did find my index with the name I had given and something like a prefix would usually mean it will not effect your `model::search()` method as the prefix should be implicitly handled by the package.

and I am rather new with elastic search. Still trying to figure out everything with trial and error. I am not the appropriate person to answer your question nor do I have the answer. Sorry! and thank you for your helpfulness. I shall not leave your solution unturned :)

**Comment by alvibd** [comment]
hi @jlstandout , I seems I had to restart my elasticsearch for reason unknown to science. I also found out that the `_write` is added to your index alias name.

**Comment by farshadff** [comment]
> Maybe it's related with issue what I have?
> I have index UserIndexConfigurator
> 
> ```
> <?php
> namespace App\Searchable;
> use ScoutElastic\IndexConfigurator;
> use ScoutElastic\Migratable;
> class UserIndexConfigurator extends IndexConfigurator
> {
>     use Migratable;
>     protected $name = 'users';
>     /**
>      * @var array
>      */
>     protected $settings = [
>         //
>     ];
> }
> ```
> 
> And index is prefixed with `SCOUT_PREFIX=dev_dev_`.
> And then i tried to seed 100 users. I also didn't have any results, when i tried to check users, but then i noticed, that users where added to `dev_dev_users_write` index with type `dev_dev_users`, but when i try to search them, they are searched in index `dev_dev_users`.
> Can someone explain me why sometimes items are postfixed with `_write` and sometimes not?
> 
> **alvibd** I would recommend you to inspect your query and check if index matches with real document index. My guess is that your documents are under `*_write` index.
> 
> You can check document index with GET request `localhost:9200/_search`.

did you solved this problem ???

**Comment by alvibd** [comment]
Yes.

**Comment by farshadff** [comment]
> I solved my problem. But not the one you are referring to

i have the same problem that my result returns empty all the time but i can see the in an index but with _write prefix i dont know how to fix that any advise you can give me ??

**Comment by alvibd** [comment]
Try restarting your elasticsearch service. “ sudo systemctl restart elasticsearc“

**Comment by farshadff** [comment]
@alvibd i did that but i was not lucky with that . i dont know what and where is the problem !!!
