### ISSUE TITLE
Why is database being queried for search?

### ISSUE THREAD

**Issue by TheBigK** [babenkoivan/scout-elasticsearch-driver#161]
I see that whenever I perform search, the database is still getting queried. For example, I have this -

`User::search($keywords)->take(5)->get();`

I see that when the search is performed, following query is executed 

`select * from `users` where `id` in ('1', '2', '3', '4', '5);`

Is there any way to avoid querying database? Or this behavior is expected?

**Comment by michaelnguyen547** [comment]
it is intended by default. Check out #116 for more info

**Comment by iget-esoares** [comment]
Duplicated of #116. Closing it.
