### ISSUE TITLE
query to database is not logged to Telescope

### ISSUE THREAD

**Issue by michaelnguyen547** [babenkoivan/scout-elasticsearch-driver#165]
I know the fact that database is being queried to retrieve the Eloquent model, but there is no query logged in Telescope. 

FYI, Scout (Algolia) logs database queries to Telescope.

**Comment by iget-esoares** [comment]
Hi @michaelnguyen547

This looks not like a problem in this package, but on Laravel Telescope itself. 

This package just use Laravel DB facade and Eloquent itself, so Telescope should cover any calls.

Are you sure that's nothing different between algolia environment and our elastic search one? Is the same project?

I'll close this issue for clean up reasons, but feel free to comment on it calling my name if you thing this still a bug.
