### ISSUE TITLE
Bulk indexing?

### ISSUE THREAD

**Issue by jorgenb** [babenkoivan/scout-elasticsearch-driver#17]
@babenkoivan 

Is it possible to enable bulk indexing with this driver?

See: https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_indexing_documents.html#_bulk_indexing

**Comment by babenkoivan** [comment]
Hi @jorgenb, unfortunately it's not possible. You can save only one record at the same time.

**Comment by jorgenb** [comment]
I see. Would you be open to a PR that solves it without breaking anything? If so, were would be a good place to start?

**Comment by babenkoivan** [comment]
@jorgenb I've started working on a solution, but it will take some time.. I'm currently relocating to another country, so I can't dedicate much time to the project right now. Hope it'll be ready till next weekend.

**Comment by babenkoivan** [comment]
Hi @jorgenb, I released a new version - 2.2.0. A new option (`indexer`) is now available in the `config/scout_elastic.php` file. It can be either `single` (by default) or `bulk`. Also you can change batch size by modifying the chunk option in the `config/scout.php`.

If you want just to add / delete a collection of models into / from index, you can call searchable / unsearchable method on the collection:

```php
$models->searchable();
$models->unsearchable();
```
