### ISSUE TITLE
Hydrate models (with no database)

### ISSUE THREAD

**Issue by robsontenorio** [babenkoivan/scout-elasticsearch-driver#172]
This is very usefull when you project does not have a database and you don’t wanna lose Eloquent's power. 

Would you accept a PR?

https://github.com/laravel/scout/issues/213#issuecomment-316846816

**Comment by clovenlife** [comment]
I would love for this to be implemented. I'm working with the raw in a few places because the mysql overhead was redundant. This would minimize any confusion for anyone working on this code after me.

**Comment by iget-esoares** [comment]
Duplicated of #116. Closing it.
