### ISSUE TITLE
Conflict with my models 'highlight' attribute and Searchable trait

### ISSUE THREAD

**Issue by vedmant** [babenkoivan/scout-elasticsearch-driver#178]
In my post model I have attribute 'highlight' and it looks like it conflicts with setHighlightAttribute method in Searchable trait. What's better way to resolve this? Should I override trait's setHighlightAttribute in my model?

**Comment by oixan** [comment]
This is not related with the package but is a traits problem. Anyway you can use alias.

```<?php
trait A {
    public function smallTalk() {
        echo 'a';
    }
    public function bigTalk() {
        echo 'A';
    }
}

trait B {
    public function smallTalk() {
        echo 'b';
    }
    public function bigTalk() {
        echo 'B';
    }
}

class Talker {
    use A, B {
        B::smallTalk insteadof A;
        A::bigTalk insteadof B;
    }
}

class Aliased_Talker {
    use A, B {
        B::smallTalk insteadof A;
        A::bigTalk insteadof B;
        B::bigTalk as talk;
    }
}
?>

**Comment by vedmant** [comment]
Makes sense, for now I just overridden setHighlightAttribute and getHighlightAttribute in my model to get actual value. Generally I think it would be better to use something more specific in the trait, like 'elastic_highlight' with setElasticHighlightAttribute, getElasticHighlightAttribute so it's less chances it will conflict with model database property.

**Comment by iget-esoares** [comment]
Hi @vedmant 

I'm closing this issue since it's a help question, just to make things cleaner here.
If you find any bug, or need some feature, fell free to create an new issue.
