### ISSUE TITLE
how combine searchRaw with searchBuilder

### ISSUE THREAD

**Issue by maralbe** [babenkoivan/scout-elasticsearch-driver#19]
Hi @babenkoivan 
I have create an array of bool query.. that is kindly complicated and depend on user search, it changes.. except the query that user want to search; user can select multiple values and search by them synchronously, now in my search query if I use `SearchRaw` method.. the results is fine.. but I can't do any `OrderBy()` or `Pagination` on my result..
I try using rules but apparently I had to use `$myModel::search($query)->rule($myRule)` 
I mean I wont to write query there.. because I have to use different elastic queries on my query..

so can you give me any solution to write my own query?

thanks in advanced

**Comment by babenkoivan** [comment]
Hi @maralbe,

I think that search rules is what you are looking for. You can specify several search rules in one model (either in a model or in a query). Each search rule has the `isApplicable` method, you can check in this method if a rule can be applied to your query (for example, by query string).
