### ISSUE TITLE
Scout 7.x Compatibility

### ISSUE THREAD

**Issue by hanspagel** [babenkoivan/scout-elasticsearch-driver#192]
Laravel Scout 7 is out. Following the [release notes](https://github.com/laravel/scout/releases) there should be no breaking changes for the elasticsearch driver. Any chance you could bump up the version?

**Comment by refucktor** [comment]
Please @babenkoivan can we have any progress on this! We will really appreciate the update

**Comment by hanspagel** [comment]
I guess we'll have to wait until a new maintainer is found.

**Comment by babenkoivan** [comment]
Added Scout 7 support in v3.10.0.

**Comment by refucktor** [comment]
> Added Scout 7 support in v3.10.0.

Highly appreciated!
