### ISSUE TITLE
Advice rather than issue, Is passport:import needed on already existing index with 35+ million records?

### ISSUE THREAD

**Issue by BirdyUK** [babenkoivan/scout-elasticsearch-driver#2]
As the title suggests, I already have an elasticsearch instance running with over 35 million records. Everything runs as one would expect but i am fairly new to the ES world so i use a paid for service to host the ES instance (Amazon AWS).

Do i still need to use the laravel scout:import command with this package or with scout in general as i tried this on a test server (Without this package) and the import was painfully slow yet the server resources was only at 1% so i assumed it was the way scout:import works.

I would be eager to test this package on the 35+ million records if it is possible to use my existing index without the need to import and basically use the package like a wrapper to make life easier with making laravel talk to ES.

One last thing i must stress, My ElasticSearch index is not indentical to my Database version as i only imported the required columns from mysql to ES so my index only returns the two values i need and is mainly used for full text search, The returned values for example would be a title and an id so on select we can fetch the true record from mysql.

That all said, Do you thing your scout driver would work or do i certainly have to do scout:import when there is already the index in ElasticSearch?

Thanks.

**Comment by babenkoivan** [comment]
Hi @BirdyUK, thank you for your interest to the package!

Did you mean `scout:import` in the title? I suppose so. 

The `scout:import` command imports 500 records in ES at once and I presume that you either don't use queues or have only one worker. To increase the indexing speed try to use queues and about 5-10 workers. You can find all necessary information in the [docs](https://laravel.com/docs/5.4/queues).

But, you don't need to import the data if you already have it in ES. You can just install the package, configure a connection to ES, specify the mapping for the fields and start doing search requests. But be careful, I wouldn't recommend you to use it in production at first, play with it on some test environment to not to damage your data.

You have mentioned that your ES data is not identical to DB data, that's not a problem! You can determine the `toSearchableArray` method in your model. It has to return the data to index, like this:

```
public function toSearchableArray()
{
    return [
        'id' => $this->id,
        'title' => $this->title
    ];
}
```

I hope it will work for you, but if you get any troubles let me know on my email babenko.i.a@gmail.com and I'll try to help you. 

Sorry, this's not an issue connected to the package, so I'll close it.

**Comment by jpujol880807** [comment]
Hi I'm trying to import 20 millons of records with php artisan scout:import "App\MYModel", it's too slow , I'm looking how to create several queue workers to do the but haven't found an example in the web. I'm not familiar with queues in laravel can you post an example of importing data using queue workers.

**Comment by babenkoivan** [comment]
Hi, @jpujol880807, I can only provide you with a couple of links. 

First of all, install queues. I recommend you to install Beanstalkd. Here is the link to the official docs https://laravel.com/docs/5.4/queues. Don't forget to run `php artisan queue:work` after configuring a queue driver. 

Then, configure scout to use queues. Here is the link how to do that https://laravel.com/docs/5.4/scout#queueing.

After those steps indexing has to be faster.

**Comment by jpujol880807** [comment]
thanks to your advice i figured oud how to get the queue:work up and running i missed some configuration steps, now it's incredible fast when  i use scout:import, by the way this driver roks it should be at the top in google when i search for scout elastic driver it's the most complete solution i found.
