### ISSUE TITLE
Accessing related data on a modal

### ISSUE THREAD

**Issue by atmediauk** [babenkoivan/scout-elasticsearch-driver#20]
Hello,

Just had a question about accessing related model data. Using Laravel Scouts ```toSearchableArray``` I am able to append related **source** data in my News model. For example:

```
    /**
     * Get the indexable data array for the model.
     *
     * @return array
     */
    public function toSearchableArray()
    {
        $array = $this->toArray();

        $array['source'] = $this->source;
        return $array;
    }

```
I then create the index and import into elastic search via the command line.

This all works great. When I access ES via Postman I see the news with **source** data correctly however when I try and access it in my controller using the code below it does not retrieve the related **source** data, only the news data.

```
        return News::search('*')
            ->orderBy('published_at', 'desc')
            ->take(100)
            ->get();

```

Any ideas why this might be? Thanks for your help.

**Comment by babenkoivan** [comment]
Hi @atmediauk ,

You have to use Eloquent relations, to get data. The search method will only return you a News object.

**Comment by atmediauk** [comment]
@babenkoivan thanks for getting back to me.

Sorry if im being stupid but using Laravel Scouts toSearchableArray method I am able to successfully add my related modal data in to the ES index e.g after I create my index and run scout::import "App\News" I see this in Postman - http://jmp.sh/PuHtHOt

Which is good, red box is my source data (related model) and is added. That means my related data is inside ES. But my problem is I cant seem to access the "source" data when using **News::search('*')**

For example if I do 

```
 return News::search('*')
            ->orderBy('published_at', 'desc')
            ->take(100)
            ->get();
```
It returns everything except the **source** which is weird because it is definitely inside ES.

Hopefully that makes sense. Thanks again for your input.

**Comment by babenkoivan** [comment]
Yes, you are absolutely correct. You can put anything in ES: your model fields or any related data. But when you call the search method you can only retrieve the model itself, that correspond to the search query. For example, you can do the following:

```php
News::search('*')
    ->where('source.tags', 'newspapers')
    ->get();
```

It will return you a collection of News. If you want to get Sources you have to either do a search on a Source model or use Eloquent relations on News like:

```php
News::search('*')
    ->where('source.tags', 'newspapers')
    ->first()
    ->sources();
```
Scout doesn't provide you with a direct access to ES. It makes request to ES to get model ids and then gets data from DB. If you want a direct access, have a look at `searchRaw` method.

Hope I answered your question.

**Comment by atmediauk** [comment]
Thanks for the clarification. I didn't realise that it would have to be eager loaded separately.

Thanks again for the great package!
