### ISSUE TITLE
Boosting by Popularity

### ISSUE THREAD

**Issue by whollaus** [babenkoivan/scout-elasticsearch-driver#203]
Is there a way to use the "Boosting by Popularity" function?
https://www.elastic.co/guide/en/elasticsearch/guide/current/boosting-by-popularity.html

Currently i'm using the oderBy function. But it's not the same.

Thank you very much.

**Comment by iget-master** [comment]
I think it actually doesn't depends on any changes in this package.

You search rule should contain the query as described on Elasticsearch docs, and you are responsible for increment the Popularity field.

**Comment by iget-esoares** [comment]
Hi @whollaus. 

I'm closing this issue since it's a help question, just to make things cleaner here.
If you find any bug, or need some feature, fell free to create an new issue.
