### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::searchable()

### ISSUE THREAD

**Issue by kingjian0801** [babenkoivan/scout-elasticsearch-driver#205]
In a model that references traits,like this:
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use ScoutElastic\Searchable;

class Asset extends Model
{
    use Searchable;
    use Traits\ImportExcel;
    use Traits\DataHandling;
    use Traits\GenerateReport;

    public $timestamps = false;

    protected $indexConfigurator = AssetIndexConfigurator::class;
    
    .....
```

 it will report an error: 
`Call to undefined method Illuminate\Database\Query\Builder::searchable(), `

After commenting on traits, I can import data to es.
how to solve it?

**Comment by iget-esoares** [comment]
Could you please show the line where you call `searchable()` method? Also, describe the steps you are doing that result on this error.

**Comment by iget-esoares** [comment]
Closing this issue due lack of activity. Feel free to ask for a reopen if this is still an issue.
