### ISSUE TITLE
Illegal Argument Exception - Error with mapping

### ISSUE THREAD

**Issue by anbu369** [babenkoivan/scout-elasticsearch-driver#214]
Hi,

This is my mapping

`protected $mapping = [
        'properties' => [
            'id' => [
                'type' => 'integer',
                'index' => 'not_analyzed'
            ],
            'skill_name' => [
                'type' => 'string',
                'analyzer' => 'english'
            ],
            'alias' => [
                'type' => 'string',
                'analyzer' => 'english'
            ],
            'company_ids' => [
                'type' => 'string',
                'index' => 'not_analyzed'
            ],
            'ancestor_names' => [
                'type' => 'string',
                'index' => 'not_analyzed'
            ],
        ]
    ];`

When I update the elastic mapping, I get the following error

` {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types ca
  nnot be provided in put mapping requests, unless the include_type_name parameter is set to true."},"status":400}`

**Comment by iget-esoares** [comment]
What's your Elasticsearch version?

**Comment by iget-esoares** [comment]
If you are using 7.0, see this: https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-put-mapping.html

> Before 7.0.0, the mappings definition used to include a type name. Although specifying types in requests is now deprecated, a type can still be provided if the request parameter include_type_name is set. For more details, please see Removal of mapping types.

**Comment by anbu369** [comment]
@iget-esoares Hi, thanks for the reply. I am using 7.0. I see that the mapping types are removed so in that case, what do I do now?

**Comment by maarten00** [comment]
> If you are using 7.0, see this: https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-put-mapping.html
> 
> > Before 7.0.0, the mappings definition used to include a type name. Although specifying types in requests is now deprecated, a type can still be provided if the request parameter include_type_name is set. For more details, please see [Removal of mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html).

Are there any plans to add compatibility with 7.* and 8.* releases? For version 8 the include_type_name will no longer be supported: 
https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html#_schedule_for_removal_of_mapping_types

I'd open up a PR, but I'm new to Scout and this driver, so I don't think I'd be comfortable enough with the use cases and the codebase.

**Comment by iget-esoares** [comment]
I had no time to read the release notes for 7.0 yet, but will do and figure out what's the replacement for type. It's just not needed anymore?

**Comment by maarten00** [comment]
In short the idea for 8.x is as follows; Every index can only contain one document type. If you want to use multiple types, you have to use a seperate index for each type. This driver uses `_default_` as mapping type, which was deprecated in 6.x and throws an error in 7.x. (which can be silienced with a query param) Passing a type when indexing a document is also deprecated in 7.x and will throw an error in 8.x. Passing a query param to avoid the warnings/errors will no longer be possible.

You can find the full rundown here: https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html

**Comment by babenkoivan** [comment]
Hi all, I'd say we need to go with the `include_type_name=true` parameter now and remove the `_default_` mapping. It'd allow us to use ES 6.7 and ES 7 at the same time. Later on we need to remove types completely, but it requires a deep refactoring.

**Comment by greggh** [comment]
Just started with Scout, this driver, and ElasticSearch today.  Started with installing ES and getting used to configuring it on the server. That gave me ES 7. What do I need to do differently than the documents here, to get this working?

**Comment by anbu369** [comment]
thanks for all the reply guys. I am new to ES and Scout as well. Currently, I downgraded to ES 6.7 to make the driver work. @greggh I am not sure how to make the driver work with ES 7 so resorted to 6.7. Please do let know in this thread if you figure out how to make the driver work for ES 7. Thanks

**Comment by greggh** [comment]
@iget-esoares or @babenkoivan, should I just wait a day or so and you'll have an update, then I go forward with 7.0. Or should I do the work to downgrade to 6.7 because it's going to be a while?

Also, thanks for the awesome driver.

**Comment by babenkoivan** [comment]
I'd say, it's better to go with ES 6.7 for now. In our driver we use [Elasticsearch-PHP](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/index.html) as a dependency. Current supported version of Elasticsearch-PHP is 6.5.x, we need to wait until they release 7.x support.
Even if we adjust the driver itself, some features might not work stable / as expected.

**Comment by anbu369** [comment]
in case anyone has problem downgrading to 6.7 from 7, uninstall elastic 7 and delete c:\ProgramDat\Elastic as well before installing 6.7

**Comment by iget-master** [comment]
> @iget-esoares or @babenkoivan, should I just wait a day or so and you'll have an update, then I go forward with 7.0. Or should I do the work to downgrade to 6.7 because it's going to be a while?
> 
> Also, thanks for the awesome driver.

I'm an early adopter, but since there other dependencies that wasn't updated for this package work right on 7.0, we should sit and wait before upgrading to it. :-(

**Comment by greggh** [comment]
Thanks for the responses. I usually am an early adopter too, but downgrading to 6.7 seems to be the smart move. Just finished that. I'll watch the repo for updates :)

**Comment by mauxtin** [comment]
For reference:
https://github.com/elastic/elasticsearch-php/issues/865
https://github.com/elastic/elasticsearch-php/issues/880

**Comment by alinr2** [comment]
I am facing the same problem, since I also want to use 7.0.
Probably a very easy to answer question:
How can I use the parameter include_type_name=true?
Where should I use it in my code?
In MyindexIndexConfigurator?
In my Model?
And how to add this parameter?

If there is no possibility, I probably also need to downgrade to 6.7

Thank you in advanced.

**Comment by superern** [comment]
I migrated here. While this lovely package doesnt support it yet, we can try this. [supports ES7](https://github.com/matchish/laravel-scout-elasticsearch)

**Comment by babenkoivan** [comment]
ES 7 support is added in `v3.11.0`.
If you face any issues with the new version, please open a new thread.

**Comment by babenkoivan** [comment]
Hi guys, it was a mistake from my side to release ES7 support as `v3`, because it's not back compatible. To fix it, I reverted ES7 support in `v3.12` and released a new version `v4.0`. Please update to `v4.0` if you want to use ES7.

**Comment by rudolphp** [comment]
> I am facing the same problem, since I also want to use 7.0.
> Probably a very easy to answer question:
> How can I use the parameter include_type_name=true?
> Where should I use it in my code?
> In MyindexIndexConfigurator?
> In my Model?
> And how to add this parameter?
> 
> If there is no possibility, I probably also need to downgrade to 6.7
> 
> Thank you in advanced.

You specify it in the Model mapping
`protected $mapping = [
        "include_type_name" => true,
...
`

**Comment by aceArt-GmbH** [comment]
I don't get it to work with the 7.0 and the new v4.0 branch. 

I tried this: 
`protected $mapping = [
        "include_type_name" => true,
        'properties' => [
            'content' => [
                "analyzer" => "standard",
                'type' => 'text'
            ],
        ]
    ];`

But after I triggered the update-mapping function by artisan there occurs following error message:
`Root mapping definition has unsupported parameters:  [include_type_name : true]"`.

Without the "include_type_name" parameter there is a error message after scout:import:
`Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true.`

Thank you very much for your help!

**Comment by babenkoivan** [comment]
@aceArt-GmbH you don't need to specify `include_type_name` in your mapping. Please check, that you use v4 of the package and `elasticsearch/elasticsearch` is v7 or above in the `composer.lock` file.

If everything is correct, can you please share your exact Elastic Search version, Laravel version and PHP version, as long as the command you are trying to execute.

**Comment by aceArt-GmbH** [comment]
@babenkoivan, the composer.lock file shows that it includes v7.0.2 of elasticsearch/elasticsearch and v4.0.0 of your extension. So it should be correct. The Elastic Search version is 7.2.0. PHP 7.2.19 and laravel 5.8.27. After restarting the server the commands (Without the _include_type_name_ parameter) work  without an error. But there are no entities in the search. I tried:

```
php artisan elastic:drop-index "App\Index\AdvertIndexConfigurator"
php artisan elastic:create-index "App\Index\AdvertIndexConfigurator"
php artisan elastic:update-mapping "App\Models\Advert" -v
php artisan scout:import "App\Models\Advert"
```
which generates that output:
```
The index advert was deleted!
The advert index was created!
The advert_write alias for the advert index was created!
The adverts mapping was updated!
Imported [App\Models\Advert] models up to ID: 208
All [App\Models\Advert] records have been imported.
```
But when I call `curl http://localhost:9200/advert/type/_count` you can see that there are no entries.
`{"count":0,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0}}`

In the Advert Model I use this configuration (Besides using Searchable as Trait):
```
    protected $indexConfigurator = \App\Index\AdvertIndexConfigurator::class;
    protected $saerchRules = [];
    protected $mapping = [
        'properties' => [
            'content' => [
                'type' => 'text'
            ],
        ]
    ];
```
And the AdvertIndexController:
```
namespace App\Index;

use ScoutElastic\IndexConfigurator;
use ScoutElastic\Migratable;

class AdvertIndexConfigurator extends IndexConfigurator
{
    use Migratable;

    /**
     * @var array
     */
    protected $settings = [
    ];
}

```
Do you have any glue?
Thank you very much

**Comment by babenkoivan** [comment]
@aceArt-GmbH I believe, that the correct url is `curl http://localhost:9200/advert/adverts/_count`.

Try to execute the following code in Tinker: `App\Models\Advert::search('*')->get()` does it return any response? 

Also you have a typo in the `protected $saerchRules = [];` line.

**Comment by aceArt-GmbH** [comment]
@babenkoivan it works! thank you very much for your help!

**Comment by Saurav-Jain16** [comment]
I am using this regex for email (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])

Exception is coming "caused_by":{"type":"illegal_argument_exception","reason":"invalid range: from (126) cannot be > to (93)"}}}]},"status":400}

This is request

{
  "bool" : {
    "must" : [
      {
        "bool" : {
          "must" : [
            {
              "regexp" : {
                "email" : {
                  "value" : "(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])",
                  "flags_value" : 65535,
                  "max_determinized_states" : 10000,
                  "boost" : 1.0
                }
              }
            }
          ],
          "adjust_pure_negative" : true,
          "boost" : 1.0
        }
      }
    ],
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}
