### ISSUE TITLE
Mapping documentation

### ISSUE THREAD

**Issue by greggh** [babenkoivan/scout-elasticsearch-driver#219]
This part of the documentation doesn't make any sense to me on first read:

```
    protected $mapping = [
        'properties' => [
            'text' => [
                'type' => 'text',
                'fields' => [
                    'raw' => [
                        'type' => 'keyword',
                    ]
                ]
            ],
        ]
    ];
```

Looking at this and the official documentation, it looks like the first 'text' is actually what you have named your example column? That's a bit confusing to the first time reader, with the type also being 'text'.

So if I am reading that right then 'text' is the name, and 'text' is the type. But then whats the 'fields' array all about? I don't see it mentioned anywhere else in your documentation, or on your old medium post about this, here: [https://medium.com/@babenko.i.a/how-to-make-laravel-and-elasticsearch-become-friends-55ed7690331c](https://medium.com/@babenko.i.a/how-to-make-laravel-and-elasticsearch-become-friends-55ed7690331c)

If I read deeper into documentation, it might be that the column named 'text' in my database is of type 'text' and the 'fields' is saying that it should be interpreted as JSON data? And then 'raw' is a key/value in that JSON data, and you're giving it type 'keyword'?

It would be really awesome to actually have that "protected $mapping" actually explained out a bit more.

**Comment by babenkoivan** [comment]
@greggh I've added some more details to model mapping example. Hope now it makes more sense.

**Comment by greggh** [comment]
That is perfect. Just the right amount of information to make it intuitive. Thank you!
