### ISSUE TITLE
Full text search not working

### ISSUE THREAD

**Issue by anbu369** [babenkoivan/scout-elasticsearch-driver#220]
Hi, I am using the following query

`$search = Refine::search($request->get('q'))->get();`

In the index, I have Android, iOS, Windows. When the search query is 'Andr', the search is not returning 'Android' unless I search for the full term. Is there any option to be changed for full-text?

Thanks.

**Comment by boolfalse** [comment]
In search rules add "fuzziness", like this:
```php
public function buildQueryPayload() {
        return  [
            'should' => [
                ['match' => [
                    'title' => [
                        'query' => $this->builder->query,
                        'fuzziness' => 2,
                    ]
                ]],
            ],
        ];
    }
```
But this is not actually what you want, but may it can help you for your project

**Comment by anbu369** [comment]
I figured it out, I used match_phrase_prefix to do wild card query

`public function buildQueryPayload()
    {
        return [
            'must' => [
                'match_phrase_prefix' => [
                    'skill_name' => $this->builder->query
                ]
            ]
        ];
    }`
