### ISSUE TITLE
After create-index, update-mapping, scout:import adds more fields to index?

### ISSUE THREAD

**Issue by greggh** [babenkoivan/scout-elasticsearch-driver#221]
**Versions**

- scout-elastic-driver: 3.10
- laravel/framwork: 5.8.13
- php: 7.3.4
- elasticsearch: 6.7.1

**Description**

I have 89 tables, for 88 of them, everything worked great. For 1, the most important one in the database, it is acting strange. I make all the code changes, create the index configurator and search rules, and then run the elastic:create-index and elastic:update-mapping. Both of those work fine. Looking in Elastic Search, the correct index and mapping is there.

Then I run scout:import and suddenly that index and mapping pair have every field from the table, instead of just the ones I configured in my $mapping and search rule. Then one of those fields, which is sometimes json, fails with errors. I don't even want that field indexing so I don't really care about the error, I just want it to stop attempting at all.

The app is an internal CRM that has a lot of extra knowledge of our clients websites.

In the Website.php (laravel model)
```
    protected $indexConfigurator = \App\SearchIndexes\WebsiteIndexConfigurator::class;

    protected $searchRules = [
        \App\SearchRules\WebsiteSearchRule::class
    ];

    protected $mapping = [
        'properties' => [
            'url' => [
                'type' => 'text',
            ],
            'company_name' => [
                'type' => 'text',
            ],
            'logo_url' => [
                'type' => 'text',
            ],
            'title' => [
                'type' => 'text',
            ],
            'meta_description' => [
                'type' => 'text',
            ],
            'newest_year' => [
                'type' => 'keyword',
            ],
            'wordpress_version' => [
                'type' => 'keyword',
            ],
            'industry' => [
                'type' => 'text',
            ],
            'founded_year' => [
                'type' => 'keyword',
            ],
        ]
    ];

```

\App\SearchIndexes\WebsiteIndexConfigurator
```
Default from this package, no edits.
```

\App\SearchRules\WebsiteSearchRule
```
<?php

namespace App\SearchRules;

use ScoutElastic\SearchRule;

class WebsiteSearchRule extends SearchRule
{
    public function buildQueryPayload()
    {
        $query = $this->builder->query;

        return [
            'must' => [
                [
                    'match' => [
                        'url' => $query,
                    ],
                ],
                [
                    'match' => [
                        'company_name' => $query,
                    ],
                ],
                [
                    'match' => [
                        'logo_url' => $query,
                    ],
                ],
                [
                    'match' => [
                        'title' => $query,
                    ],
                ],
                [
                    'match' => [
                        'meta_description' => $query,
                    ],
                ],
                [
                    'match' => [
                        'newest_year' => $query,
                    ],
                ],
                [
                    'match' => [
                        'wordpress_version' => $query,
                    ],
                ],
                [
                    'match' => [
                        'industry' => $query,
                    ],
                ],
                [
                    'match' => [
                        'founded_year' => $query,
                    ],
                ],
            ],
        ];
    }
}

```

**Steps to reproduce**

The command prompt:
```
forge@host:~/current$ php artisan elastic:create-index App\\SearchIndexes\\WebsiteIndexConfigurator
The website index was created!
The website_write alias for the website index was created!
forge@host:~/current$ php artisan elastic:update-mapping App\\Website
The websites mapping was updated!
forge@host:~/current$ php artisan scout:import App\\Website
Imported [App\Website] models up to ID: 8855
```

I am using Horizon and queues for my importing. So that Imported line repeats a few thousand times.

P.S. This driver is awesome, and for all of the stuff is it currently working on (88 of the 89 tables) it is amazing, thank you for all this work.

**Comment by babenkoivan** [comment]
Hi, the mapping property is only to specify field types and meta data for ES, it doesn’t mean, that only these fields appear in ES index. You need to define fields in ‘toSearchableArray’ method of your model. Check https://laravel.com/docs/5.8/scout#configuring-searchable-data for more info.

**Comment by greggh** [comment]
That makes sense. I really appreciate the help here. So for my use-case, it looks like I need to basically create a toSearchableArray that returns the same list that I have put in the mapping. That will accomplish what I am looking for.
