### ISSUE TITLE
Perform a global search over different entity types

### ISSUE THREAD

**Issue by Marian0** [babenkoivan/scout-elasticsearch-driver#224]
Hi guys,

I've installed, configured and started using this package. I've also integrated with my docker installation and everything went fine.

I'm just curious about if it is possible to perform like a global search over different models, for example if I have a Post and a Category models, are there any way to search in both models instead of using:

```
Post::search('keyword')->get();
Category::search('keyword')->get();
```

Thank you!

**Comment by babenkoivan** [comment]
Hey @Marian0,
Unfortunately, it's not possible with Scout.
