### ISSUE TITLE
Argument 1 passed to App\Product::setHighlightAttribute() must be an instance of ScoutElastic\Highlight

### ISSUE THREAD

**Issue by MosamIndiaNIC** [babenkoivan/scout-elasticsearch-driver#229]
I am using this library in my project front side for searching but it gives me the above error while I am updating my products at admin side.
I have included this library in my product model.

**Comment by khanhvu14** [comment]
If you have a highlight column your product table, temporary change it to another name.

**Comment by MosamIndiaNIC** [comment]
I have tried that already but still facing the same issue

**Comment by MosamIndiaNIC** [comment]
Thank you. It is working now
