### ISSUE TITLE
Where clause not working.

### ISSUE THREAD

**Issue by MosamIndiaNIC** [babenkoivan/scout-elasticsearch-driver#230]
Below is my code, in which when soer_by found as a 'featured' it will apply where clause.
and unfortunately, it is not working. it is giving me a blank array.

I found that scout is only provided where clause on basic numeric equality checks. Since a search index is not a relational database, more advanced "where" clauses are not currently supported

But In this library, it is given that where clauses on a string value.

It would be appreciated if anyone could help me out. 
below is my code 
```
 $search = (!is_null($search) && $search != "")? $search: '*';
        $prods = Product::search($search);
        $prods->with(['category', 'allProductSku','productDefaultSku', 'productDefaultVariationSku',
            'productSkuImages',  'productImages','campaignExclusiveProducts.campaignRelation', 'vendorData'
        ]);
        if($category_id){
            $arrayCat = General::categoryPathArrayElasticSearch($category_id);
            $prods->whereIn('product_categorty.id',array_values($arrayCat));
        }
        if ($sort_by) {
            if ($sort_by == 'featured') {
                $prods->where('featured', 'Yes');
            } else if ($sort_by == 'asc' || $sort_by == 'desc') {
                $prods->orderBy('final_price', $sort_by);
            } else if ($sort_by == 'null') {
                $prods->orderBy('id','desc');
            }
        }
        $per_page =  ($per_page > 48) ? 48: $per_page;
        $prods = $prods->paginate($per_page);
```

**Comment by MosamIndiaNIC** [comment]
I have solved my issue by storing featured column data in integer datatype in the elastic-search document and the where clause is working properly

**Comment by iget-esoares** [comment]
Closing this issue since you figured out how to solve. Feel free to ask for a reopen if you think it's an issue.

**Comment by MosamIndiaNIC** [comment]
But I want a solution for applying where clause for string or text value

**Comment by loic-lopez** [comment]
@iget-esoares How I can perform a where clause with an UUID?

**Comment by sanasol** [comment]
To make `where()` work need use property type `keyword` or add `raw` with keyword type for mapping.

```
'city' => [
    'type' => 'text',
    'fields' => [
        'raw' => [
            'type' => 'keyword',
        ]
    ]
]
```
`$query->where('city.raw', 'CityName');`


**or**

```
'city' => [
    'type' => 'keyword',
],
```
`$query->where('city', 'CityName');`
