### ISSUE TITLE
Search rule is not applying when query string is not pass

### ISSUE THREAD

**Issue by MosamIndiaNIC** [babenkoivan/scout-elasticsearch-driver#233]
Here is the rules : 
public function buildQueryPayload()
    {
      //$this->builder->query will give the search sting
        return [
            'must' => [
                  ['multi_match' => [
                      'query' => $this->builder->query,
                      'fields' => 
       ['campaign_title','description','tagAssociate.tag_name','owner.first_name','owner.last_name'],
                      "fuzziness" =>  "AUTO"
                  ]],
                  [ 'match' => [ 'active_inactive' => 'Active' ]],
                  [ 'match' => ['approved' => 'Yes']],
            ]
        ];
    }

Below is the code of the  model 

Model::search('*')->get(); 

did not apply the search rule when I pass the * in search. However, it is applying when I pass the query string into the search.

**Comment by babenkoivan** [comment]
Hi @MosamIndiaNIC, it's intended behaviour. You use `$this->builder->query` in the search rule, which is actually a string you pass to `Model::search()`. If you use '*' as a query string, the driver just filtrates ES records.
