### ISSUE TITLE
Document refresh

### ISSUE THREAD

**Issue by yashiroiori** [babenkoivan/scout-elasticsearch-driver#234]
It is possible to change the flight option in the configuration scout_elastic => document_refresh ??
I currently use 'wait_for' but when I try to import an xls file into the queue it is slow because we have to wait for the indexing in elasticsearch.

**Comment by babenkoivan** [comment]
@yashiroiori, you can use `Config::set('scout_elastic.document_refresh', 'false')` to change configuration on the fly.

**Comment by yashiroiori** [comment]
@babenkoivan this only affect at the moment are run queue?? Or all system are affected??
