### ISSUE TITLE
it's removing index when i am trying to migrate data

### ISSUE THREAD

**Issue by Lekinio** [babenkoivan/scout-elasticsearch-driver#239]
my test mapping 

```
protected $mapping = [
        'properties' => [
            'title' => [
                'type' => 'text',
                // Also you can configure multi-fields, more details you can find here https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html
                'fields' => [
                    'raw' => [
                        'type' => 'keyword',
                    ]
                ]
            ],
        ]
    ];
```
MyItemIndexConfigurator

```
 MyItemIndexConfigurator extends IndexConfigurator
{
    use Migratable;

    protected $name = 'items';
    /**
     * @var array
     */
    protected $settings = [

    ];
}
```
command:
php artisan elastic:migrate App\\Models\\Items\\Item items

result:

> The items index was created.
> The items mapping was updated.
> The items_write alias for the items index was created.
> Imported [App\Models\Items\Item] models up to ID: 28
> All [App\Models\Items\Item] records have been imported.

**Comment by iget-esoares** [comment]
This behavior is expected. Here's what elastic:migrate does:

        $this->isTargetIndexExists() ? $this->updateTargetIndex() : $this->createTargetIndex();
    
        $this->updateTargetIndexMapping();
    
        $this->createAliasForTargetIndex($sourceIndexConfigurator->getWriteAlias());
    
        $this->importDocumentsToTargetIndex();
    
        $this->deleteSourceIndex();
    
        $this->createAliasForTargetIndex($sourceIndexConfigurator->getName());

It works by creating a new index, importing documents and deleting the old index.

Closing this issue since it's not actually an error. Please feel free to ask for a reopen if you still think this is an issue.

**Comment by oknoote** [comment]
When filling an initial empty index from a Elqoeunt source such as a MySQL database, there is no old index and the new index gets removed, right after the import.

The Command used:
`artisan elastic:migrate "\Ad" ads_index`

Command output:
`The ads_index index was created.
The ads_index mapping was updated.
The ads_index_write alias for the ads_index index was created.
Imported [Joinaband\Models\Ad] models up to ID: 50018
Imported [Joinaband\Models\Ad] models up to ID: 50719
Imported [Joinaband\Models\Ad] models up to ID: 51399
Imported [Joinaband\Models\Ad] models up to ID: 52085
Imported [Joinaband\Models\Ad] models up to ID: 52739
Imported [Joinaband\Models\Ad] models up to ID: 53409
Imported [Joinaband\Models\Ad] models up to ID: 54068
Imported [Joinaband\Models\Ad] models up to ID: 54749
Imported [Joinaband\Models\Ad] models up to ID: 55353
Imported [Joinaband\Models\Ad] models up to ID: 55960
Imported [Joinaband\Models\Ad] models up to ID: 56031
All [Joinaband\Models\Ad] records have been imported.
The ads_index index was removed.`

Do we need to write our own indexing methods in case we are indexing an initial batch of MySQL data to ElasticSearch?
