### ISSUE TITLE
Access hits/ total on result set

### ISSUE THREAD

**Issue by atmediauk** [babenkoivan/scout-elasticsearch-driver#24]
Hello, just checking if its possible to access the hits data on a search result? Couldn't find anything in the docs.

Thanks, this package is really cool.

**Comment by babenkoivan** [comment]
Hi @atmediauk ,

Sorry for the late reply and thank you for the good words :)

You can easily get a raw result from ES:

```php
App\MyModel::search('foo')->raw();
```
