### ISSUE TITLE
Elasticsearch 6.* trouble with include_type_name

### ISSUE THREAD

**Issue by shortcodes** [babenkoivan/scout-elasticsearch-driver#252]
After last upgrade capability of use older elasticsearch ( 6.2.3) in my case is throublesome

I followed all instructions with no werid stuff and got error:

       Elasticsearch\Common\Exceptions\BadRequest400Exception  : 
      {"error":{"root_cause": 
      [{"type":"illegal_argument_exception","reason":"request 
      [/test_rs_user_write/_mapping/test_rs_users] contains unrecognized parameter: 
      [include_type_name]"}],"type":"illegal_argument_exception","reason":"request 
      [/test_rs_user_write/_mapping/test_rs_users] contains unrecognized parameter: 
      [include_type_name]"},"status":400}

Apartntly `include_type_name` was added recently. Shouldn't it be back compaiible?

**Comment by shortcodes** [comment]
Sorry to bother. I noticed that elasticsearch package is 7.0.0 when switching from 3.10 to 3.11

**Comment by babenkoivan** [comment]
hey @shortcodes, actually you are right and this is my fault - if it's not back compatible, I had to release v4. 

It's kind of late to do that, so I'll try to make it clear in the README file.

**Comment by paligiannis** [comment]
@babenkoivan What are the steps to go back? Just replace the compose.json to 3.10?

**Comment by babenkoivan** [comment]
Hi guys, sorry for the inconvenience. We decided to revert ES7 breaking changes in the new v3.12 and release ES7 support in v4.0. I'll need to run `composer update` to fix the issue.

**Comment by babenkoivan** [comment]
Just released `v3.12.0`, please update the package and open the new thread if if you have any issues.
