### ISSUE TITLE
Problem with Collection::load function

### ISSUE THREAD

**Issue by paligiannis** [babenkoivan/scout-elasticsearch-driver#257]
**Versions**

- scout-elastic-driver: 3.12.0
- laravel/framwork: 5.8.27
- php: 7.3
- elasticsearch: 6.5.4

**Description**

I struggle to understand why even if searching works the following code does not seem to have any result.

Works and gives correct results:
`$result = Product::search($keywords)->get();`

Does not work:
`$result = Product::search($keywords)->with('getUserPricesBasedOnRole')->get();`

**What I tried**

- Change version to php 7.1,7.2
- Upgrading and downgrating the version of the package

Check the issue here 
https://staging.anelixi.com.gr/product/search/toy
The "toy" is the search query

**Steps to reproduce**

To reproduce it is very easy. 

1. Create 2 models
2. Create any kind of relation between them
3. For one these 2 models create an index, index-configurator
4. Import any data with php artisan scout:import "Your model"
5. You will see that any try of getting relation after search does not work

**What I have done so far**
1. 08-07 @iget-esoares 
Changing to             
$products = Product::with('getUserPricesBasedOnRole')->search($keywords)->get();
http://prntscr.com/oc7ita

2. 08-07 @iget-esoares works correctly
http://prntscr.com/oc8j1z
Product::with('getUserPricesBasedOnRole')->first();
http://prntscr.com/oc8jtz

3. 08-07 @iget-esoares  re-install all composer packages
composer install --prefer-source
nothing again ! -> no problem with versions or anything

4. **IMPORTANT** @iget-esoares 
I tried this
`Product::search($keywords)->first()->load('getUserPricesBasedOnRole')` It works!
**BUT**
`Product::search($keywords)->get()->load('getUserPricesBasedOnRole')` Does not work!

5.  09-07
I tried 
`Product::search($keywords)->with('getUserPricesBasedOnRole')->paginate(0)`
It works (but I want to use get(), not paginate())
http://prntscr.com/ocg52o

6. 09-07
I found a way but it's not so delicate -> I really can't understand why get() is not working. I am messing this with xdebug to find any issues. It's really hard.
`Product::search($keywords)->paginate()->load('getUserPricesBasedOnRole');`

**Comment by iget-esoares** [comment]
Please try putting the `with` method before the `search`, it works here.

**Comment by paligiannis** [comment]
> Please try putting the `with` method before the `search`, it works here.

Thank you for answer back. I tried that and I enclose the response. 
**Call to undefined method Illuminate\Database\Eloquent\Builder::search()**

**Comment by iget-esoares** [comment]
Yeah, you're right, using with before search fails.

When you do:

    $result = Product::search($keywords)->with('getUserPricesBasedOnRole')->get();

what errors do you get?

Can you show here your getUserPricesBasedOnRole relationship method?

**Comment by paligiannis** [comment]
> Yeah, you're right, using with before search fails.
> 
> When you do:
> 
> ```
> $result = Product::search($keywords)->with('getUserPricesBasedOnRole')->get();
> ```
> 
> what errors do you get?
> 
> Can you show here your `getUserPricesBasedOnRole` relationship method? (By the name, it doesn't looks like a relationship method)

Here is my error:
http://prntscr.com/oc82ex

Here is the relation -> This code checks the user role and returns a related pricelist. Then it returns the related price for the specific product.
http://prntscr.com/oc82wg

**Comment by iget-esoares** [comment]
I see no reason why it should not work.

Doing 

    $result = Product::with('getUserPricesBasedOnRole')->first();

works as expected?

**Comment by paligiannis** [comment]
> I see no reason why it should not work.
> 
> Doing
> 
> ```
> $result = Product::with('getUserPricesBasedOnRole')->first();
> ```
> 
> works as expected?

**Works as expected**
http://prntscr.com/oc8j1z
Product::with('getUserPricesBasedOnRole')->first();
http://prntscr.com/oc8jtz

**Comment by babenkoivan** [comment]
Hi @paligiannis,

I believe the problem is `getUserPricesBasedOnRole` relation. Internal Laravel mechanism expects `\Illuminate\Database\Eloquent\Relations\HasOne` to be returned from the relation method, but receives `Illuminate\Database\Eloquent\Builder` instead. It happens, because you use `hasOne` followed by `where` clause.

Please, check that if you create a relation:
```
public function price()
{
    return $this->hasOne(Price::class);
}
```

the following code is working:
```
$result = Product::search($keywords)->with('price')->get();
```

If so, try something like this:
```
$result = Product::search($keywords)->get()->load(['price' => function($query) {
    $query->where(//your custom logic here);
}]);
```

**Comment by paligiannis** [comment]
Hey there @babenkoivan, @iget-esoares  _Thank you for the prompt reply_

I just added the following relation to my Product.php model.
```
public function prices() {
   return $this->hasMany(Price::class);
}
```
and tried again
`Product::search($keywords)->with('prices')->get()`

but
`Product::with('prices')->get();`
works fine and returns correct results

**Comment by paligiannis** [comment]
> Hey there @babenkoivan, @iget-esoares _Thank you for the prompt reply_
> 
> I just added the following relation to my Product.php model.
> 
> ```
> public function prices() {
>    return $this->hasMany(Price::class);
> }
> ```
> 
> and tried again
> `Product::search($keywords)->with('prices')->get()`
> 
> but
> `Product::with('prices')->get();`
> works fine and returns correct results
> 
> Even if I tried to eager load them like so
> `Product::search($keywords)->get()->load('prices') `
> it does not work
> 
> The error is always the same.
> http://prntscr.com/ocb6hz

**Comment by paligiannis** [comment]
@babenkoivan @iget-esoares Hey there. Do you have any news? Any other issues or discussions about that?

**Comment by babenkoivan** [comment]
Hi @paligiannis,

I tried to reproduce the issue, but I didn't succeed. When you use `get` method you should receive an `Eloquent\Collection`, but you get a regular `Support\Collection` for unknown to me reason.  

Can you try to debug you code and find the place where `Support\Collection` is created? Check the call stack, starting from the `FilterBuilder::get` method and going deeper inside the package.

**Comment by paligiannis** [comment]
> Can you try to debug you code and find the place where `Support\Collection` is created? Check the call stack, starting from the `FilterBuilder::get` method and going deeper inside the package.

I really will lose my mind! http://prntscr.com/oftstj Even my IDE says that a Eloquent Collection should be returned.

**Comment by vpillinger** [comment]
@babenkoivan Line 100 of ElasticEngine.php calls `$payloadCollection = collect();`. This creates an Support\Collection class instead of an Eloquent collection.

**Comment by khanhvu14** [comment]
Anyone can add this change to new PR?

**Comment by paligiannis** [comment]
I'm closing the issue, I upgraded to 4.0.1 and everything works well.

**Comment by tantana5** [comment]
I found a solution:

$products = Product::search('keyword')->paginate(20);
$products->load('shop:id,title')->load('attributes:id,name');

return $products;
