### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by zanematthew** [babenkoivan/scout-elasticsearch-driver#26]
First, as many have said thanks, I spent some time this weekend, reading, reviewing, and installing various ES + Laravel projects. I'm settled on this one.

I have two questions, detail below;

1. My prior unit test stopped working once I added `Use Searchable;` to my model.
1. Once this package is integrated, how is unit testing expected to be handled?

---
Currently I have;
- Working unit test.
- Working scout-elasticsearch-driver with mapped types, indexes, and working results.
---

My current unit test, which works, prior to adding the `Use Searchable;` to my model does the following;

1. Refresh database
1. Create, and sign in a user via `Passport`
1. Creates several models via a factory
1. Send a post request to retrieve search results
1. Verify 200 response
1. Verify results

```
<?php

namespace Tests\Unit;

use \App\Event;
use Tests\TestCase;
use Laravel\Passport\Passport;
use Illuminate\Support\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;

class SearchEventTest extends TestCase
{
    use RefreshDatabase;

    public function setUp()
    {
        parent::setUp();
        Passport::actingAs(factory(\App\User::class)->create());
    }

    /**
     * @group search
     * @test
     */
    public function title_search() {

        factory(Event::class)->create(['title' => 'Apple',      'start_date' => Carbon::today()->toDateTimeString()]);
        factory(Event::class)->create(['title' => 'Cherry',     'start_date' => Carbon::tomorrow()->toDateTimeString()]);
        factory(Event::class)->create(['title' => 'Strawberry', 'start_date' => Carbon::yesterday()->toDateTimeString()]);
        factory(Event::class)->create(['title' => 'Blueberry',  'start_date' => Carbon::tomorrow()->toDateTimeString()]);
        factory(Event::class)->create(['title' => 'Blackberry', 'start_date' => Carbon::today()->addWeek()->toDateTimeString()]);
        factory(Event::class)->create(['title' => 'Raspberry',  'start_date' => Carbon::today()->toDateTimeString()]);

        $response = $this->post(route('search.index', [
            'type'    => 'event',
            'keyword' => 'berry'
        ]), [
            'type'    => 'event',
            'keyword' => 'berry'
        ]);

        $response
            ->assertStatus(200)
            ->assertJson([
                ['title' => 'Raspberry'],
                ['title' => 'Blueberry'],
                ['title' => 'Blackberry'],
            ]);
    }
}
```

and the endpoint, was nothing more than;

```
$results = Event::where([
    ['start_date', '>=', Carbon::today()->toDateTimeString()],
    ['title', 'like', "%{$keyword}%"],
])->with('venue.city.states')->orderBy('start_date','asc')->limit(5)->get();

return response()->json($results);
```

**Comment by zanematthew** [comment]
Actually, my failing test was related to the `toDateTimeString`, found another user in Gitter with a similar issue, after reading the error message.

**Comment by babenkoivan** [comment]
Hi @zanematthew, as I understand you fixed the issue, didn't you?

**Comment by zanematthew** [comment]
@babenkoivan sort of, passing the correct format (`toDateString`), did remove the error, however the unit test still fails. 

This seems that I'm not properly testing with Laravel Scout, as the there is no Elasticsearch content being seeded, ideally Elasticsearch and content would be mocked.

I'm closing this, as my issue seems related to Mocking ES within my unit test. If you have any resources for that please feel free to share.

**Comment by babenkoivan** [comment]
In my unit tests I mocked the ES client, that's okay for driver testing, but not for functional tests. I got good proposal here https://github.com/babenkoivan/scout-elasticsearch-driver/issues/25 and I will try to implement it when I have a time.

**Comment by marcelopm** [comment]
@zanematthew I might be wrong, but I think the issue with your tests is that after creating _searchable_ models, you are not waiting for the index to sync with the DB. I had the that issue with my functional tests and I ended up creating a trait which makes them to wait the index to be synced  after DB seeding happens. Another thing to keep in mind is that DatabaseTransaction trait won't play well with _searchable_ models. A possible solution is to make you app RDBMS agnostic and use Sqlite for creating a blueprint DB for each test, or cleaning the DB after each of them and making sure the index gets synced.

**Comment by zanematthew** [comment]
@marcelopm Thanks, I was thinking the same thing. I haven't had a chance to re-visit the test, since the release of ES 6.0, currently updating a few things first.
