### ISSUE TITLE
searchRaw is working but search is not

### ISSUE THREAD

**Issue by ForceBoot** [babenkoivan/scout-elasticsearch-driver#261]
When do:
`$item = BasicInformation::searchRaw($query);`
Can get result,But if I do
`BasicInformation::search('*')->get();`
returns nothing

and
config/scout.php, soft_delete=false

**Comment by ForceBoot** [comment]
scout-elasticsearch-driver version is v3.1,and ES 6.8

**Comment by SolStis86** [comment]
Im having this same issue

**Comment by spike-isao** [comment]
@SolStis86 So current you can get data using get()?
I have a similar issue. I could get data from explain(), but I could not use get() to get data.
ES instance: 7.1. 
scout-elasticsearch-driver: v4.0.0
elasticsearch/elasticsearch  v7.2.0

**Comment by babenkoivan** [comment]
Hi guys, @ForceBoot can you post `BasicInformation::search('*')->buildPayload()` and the $query from `BasicInformation::searchRaw($query)`?

**Comment by ForceBoot** [comment]
must use elasticsearch version >= 7.0 for this to work.
