### ISSUE TITLE
1 model with multi index

### ISSUE THREAD

**Issue by jslim89** [babenkoivan/scout-elasticsearch-driver#262]
My models supported multiple languages, I want to separate by country into multiple indexes.

E.g. `Product` model has a column `country_id`. Let say I have 10 different countries, I want to create 10 different indexes for `Product` model.

How to configure it?

**Comment by dizzersee** [comment]
@jslim89 Did you find any solution?

**Comment by dizzersee** [comment]
You could create subclasses of Product model for each language, e.g. ProductEN, ProductDE, etc. For each subclass you also create an Index Configurator. 

### Example
Product:
```
class Product extends Model
{
    // Product code
}
```

EN Product (for other languages just change EN to DE, FR, ...):
```
namespace App\Search\ProductIndices;
use App\Search\SearchableProduct;

class EN extends \App\Product
{
    use SearchableProduct;

    protected $table = 'products';

    public static $languageId = 'en; // here put your language id

    protected $indexConfigurator = ENIndexConfigurator::class;

   // This function ensures we only take EN-products by default 
   // you can also query this model like EN::all()
    public static function boot()
    {
        parent::boot();
        // Only take en products
        static::addGlobalScope(function ($query) {
            $query->where('language_id', self::$languageId);
        });
    }
}
```

EN product index configurator:

```
namespace App\Search\ProductIndices;

use ScoutElastic\IndexConfigurator;
use ScoutElastic\Migratable;

class ENIndexConfigurator extends IndexConfigurator
{
    use Migratable;

    protected $name = 'product_en_index';
    protected $settings = [
         // ...
    ];
}
```
Searchable Product trait (so you dont have to redefine mappings etc for each product language):

```

namespace App\Search;
use ScoutElastic\Searchable;

trait SearchableProduct
{
    use Searchable;


    protected $searchRules = [
        //
    ];

   
    protected $mapping = [
       //
    ];

  
    public function toSearchableArray()
    {
        $array = [
          //
        ];

        return $array;
    }
}

```

Dont forget to create the index:
`php artisan elastic:create-index "App\Search\ProductIndices\ENIndexConfigurator` 

And import all existing EN-models into it
`php artisan scout:import "App\Search\ProductIndices\EN"`

You could also automate the creation of these indices and models.

**Comment by jslim89** [comment]
@dizzersee Thanks for suggestion. I think I just differentiate by `country_id`, would be easier
