### ISSUE TITLE
Intermittent `No alive nodes found in your cluster` error

### ISSUE THREAD

**Issue by JayyWalker** [babenkoivan/scout-elasticsearch-driver#263]
**Versions**

- scout-elastic-driver:  3.10.0
- laravel/framwork: 5.7.28
- php: 7.2
- elasticsearch: 6.7.0

**Description**

I am trying to setup docker for an already existing project. However, when I attempt a scout import command, `"No alive nodes found in your cluster"` is being thrown from the `StaticNoPingConnectionPool` class. However, this does not occur for every model. 

Excluding `php artisan scout:import "App\Models\ParentMontessoriCard"`, every import will fail.

The strange thing is, if I got to `http://localhost:9200/_cluster/health`, it looks fine:
```
{
  "cluster_name": "docker-cluster",
  "status": "green",
  "timed_out": false,
  "number_of_nodes": 1,
  "number_of_data_nodes": 1,
  "active_primary_shards": 0,
  "active_shards": 0,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 0,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 100.0
}
```

**Steps to reproduce**

Using my dockerfile hereMy docker-compose.yml file is [here](https://gist.github.com/JayyWalker/448eff5eeb90744401540446d872533a). Once the containers are running, I'll run the scout import command for each of the models, like `docker-compose exec php php artisan scout:import "App\Models\Blog"`.

**Comment by iget-master** [comment]
Any errors logged on your elastic search container?

**Comment by JayyWalker** [comment]
@iget-esoares Do you mean the logging from the daemon or specific logs within the container?

**Comment by JayyWalker** [comment]
Found the problem. I didn't realise we had two drivers installed and it wasn't this one that was actually being used. 

To conclude, my issue is nothing to do with this library. 

@iget-master Thanks for your quick response, though.

**Comment by iget-master** [comment]
Thanks @JayyWalker

**Comment by NominationP** [comment]
How are you found that ?
I meet same question :((

**Comment by iget-master** [comment]
@NominationP that's usually an error on your elasticsearch cluster. Check the logs on your elasticsearch for any errors. Also check the elasticsearch host and port.
