### ISSUE TITLE
Database Query Callback Not Working

### ISSUE THREAD

**Issue by SolStis86** [babenkoivan/scout-elasticsearch-driver#265]
**Versions**

- scout-elastic-driver: latest stable
- laravel/framwork: 5.8
- php: 7.2
- elasticsearch: 7.3.0

**Description**

When trying to add database constraints using the query method, the constraints are not applied to the results.

**Steps to reproduce**

```php
MySearchableModel::search($query)
    ->query(function (Builder $builder) {
        $builder->where('column', 'value');
    });
```

**Comment by mohbakh** [comment]
+1

**Comment by iget-esoares** [comment]
The fix was merged and will be released soon

**Comment by alicompu** [comment]
> **Versions**
> 
> * scout-elastic-driver: latest stable
> * laravel/framwork: 5.8
> * php: 7.2
> * elasticsearch: 7.3.0
> 
> **Description**
> 
> When trying to add database constraints using the query method, the constraints are not applied to the results.
> 
> **Steps to reproduce**
> 
> ```
> MySearchableModel::search($query)
>     ->query(function (Builder $builder) {
>         $builder->where('column', 'value');
>     });
> ```

Worked for me
