### ISSUE TITLE
how to index all data of a model with its relations in elastic

### ISSUE THREAD

**Issue by farshadff** [babenkoivan/scout-elasticsearch-driver#275]
hi all i want to store my models with full of its relationship in a single index and show them in kibana chart when i run 
```
php artisan scout:import "nameofmode"
```
it only stores model in the index is there any way to store all relations or the relations that i want  with it too ??

**Comment by babenkoivan** [comment]
You can add any fields by your choice (even from the relations) using [`toSearchableArray` method](https://laravel.com/docs/5.7/scout#configuring-searchable-data).
