### ISSUE TITLE
Model mapping not applied at index creation

### ISSUE THREAD

**Issue by eenchev** [babenkoivan/scout-elasticsearch-driver#278]
Hello everyone. I have a searchable Laravel model. Within it, the $mapping variable is defined with all columns which should be indexed (including **created_at**).

Next, using model's index configurator, I create the index as following:
php artisan elastic:create-index App\Search\IndexConfigurators\ArticleIndexConfigurator

However, until any data is imported into the fresh index, its mapping, despite properly defined in the code, is empty and not applied. This I verify in ES by accessing ES_URL/{index}/_mapping

Because of this, if I try any search with empty ElasticSearch index, I get the following:
query_shard_exception\",\"reason\":"\**No mapping found for [created_at] in order to sort on\**",\"index_uuid\":\"NFCAQ2oJTjqOjjtjEpQOSQ\",\"index\":\"{index}"}],\"type\":\"search_phase_execution_exception\"

Any idea how to apply index mapping at index creation and not first import? Any help is appreciated.

**Comment by iget-master** [comment]
Move your mapping from model to your `IndexConfigurator` `$defaultMapping` property. Eg:

    protected $defaultMapping = [
        'properties' => [
            'all' => [
                'type' => 'text',
                'analyzer' => 'nGram_analyzer',
                'search_analyzer' => 'whitespace_analyzer',
            ],
            'name' => [
                'type' => 'text',
                'norms' => true,
                'boost' => 5,
                'analyzer' => 'exact_analyzer',
                'search_analyzer' => 'exact_analyzer',
                'copy_to' => 'all',
            ],
            'hotel_invented_name' => [
                'type' => 'text',
                'norms' => true,
                'boost' => 3,
                'analyzer' => 'exact_analyzer',
                'search_analyzer' => 'exact_analyzer',
                'copy_to' => 'all',
            ],
            'hotel_city' => [
                'type' => 'text',
                'norms' => true,
                'analyzer' => 'exact_analyzer',
                'search_analyzer' => 'exact_analyzer',
                'copy_to' => 'all',
            ],
        ]
    ];
}

**Comment by eenchev** [comment]
Thank you @iget-master , that method works flawlessly. Closing the issue.

**Comment by eenchev** [comment]
Thanks @iget-master. This method indeed creates the _default_ mapping in Elastic. However, the search issue remains.

**Comment by vpillinger** [comment]
The issue is that the mapping has to be initiated in one of two ways.
1) Manually by calling the `update-mapping` command
2) Automatically by importing at least 1 document.

So you must call the update-mapping command on your model or import at least one of the model using `php artisan scout:import <model>`.

**Comment by eenchev** [comment]
Thank you @vpillinger Running update-mapping works :+1:
