### ISSUE TITLE
comparison of two drivers

### ISSUE THREAD

**Issue by dwenaus** [babenkoivan/scout-elasticsearch-driver#28]
I'm wondering how your plugin compares with https://github.com/ErickTamayo/laravel-scout-elastic/
why did you decide to build this rather than contribute to the other one?
Does your have certain features the other doesn't and vice versa?
thanks so much for sharing!

**Comment by vesper8** [comment]
I'm also just getting into ES and was wondering the same thing but in comparison to https://github.com/basemkhirat/elasticsearch (which can also be used as a Scout driver)

From just reading the docs it seems https://github.com/basemkhirat/elasticsearch has more configuration options and some potentially useful extra artisan commands.. but I like the syntax of this package better as it feels more like a model trait.. adding the search functionality.

I haven't looked at https://github.com/ErickTamayo/laravel-scout-elastic/ yet but yes I can relate to the difficulty in picking a package when there are 3 actively developed packages that all seem to do the same thing.

Would love to hear @babenkoivan's thoughts

**Comment by babenkoivan** [comment]
Hi guys, sorry for the late reply. 

This driver - https://github.com/ErickTamayo/laravel-scout-elastic/ - doesn't provide you with artisan commands for creating index, updating mapping, etc. Also there is no such feature as search rules, so you can't tell driver how to search. I'd say that the whole [Features](https://github.com/babenkoivan/scout-elasticsearch-driver#features) sections of my README describes how my implementation differ from this driver.

This one - https://github.com/basemkhirat/elasticsearch - looks good. It's a serious work, all the differences are in details. I prefer to have mapping in your model, it's kind of related so it's nice that it's there. I have commands for migration to new mapping. And I think that search rules give you more flexibility, than just a constructor.

Hope that it'll help you to make a decision. If you have any other questions, just ask ;)
