### ISSUE TITLE
how to see all indexed data from this package 

### ISSUE THREAD

**Issue by farshadff** [babenkoivan/scout-elasticsearch-driver#283]
hi , this might be more an elastic search question but i felt like i have to first ask it here . i am trying to save a model with all relations and now its indexed but i want to see all the indexed data to see if my relation was saved or not . i wonder to know how to see all the indexed data in kibana or elastic search or even in a page in laravel . thanks in advance

**Comment by iget-master** [comment]
Use Kibana discover. Create a index pattern that matches all `*` then select it on discover tab.

**Comment by farshadff** [comment]
thanks that helped
