### ISSUE TITLE
model realtion wont save in elastic 

### ISSUE THREAD

**Issue by farshadff** [babenkoivan/scout-elasticsearch-driver#284]
i dont know if that is related to this package or not but when i use search able array like below :
```
   public function toSearchableArray()
    {
        $array = $this->toArray();
        $array['city'] = $this->city();

        return $array;
    }
```
i am sure that city relation exist on model when i run 
```
php artisan scout:import "model name"
```
the model imports successfully but the relation is empty i mean no object is getting saved there any idea which part i am doing wrong ???

**Comment by rafahernandez** [comment]
Can it be because you're using the builder instead of an object?

So it would be either
`$array['city'] = $this->city()->get();`
or
`$array['city'] = $this->city`

**Comment by farshadff** [comment]
yes thanks that solved the problem for me thanks  a lot
