### ISSUE TITLE
Indexing exclude models where column is false

### ISSUE THREAD

**Issue by chrisgrim** [babenkoivan/scout-elasticsearch-driver#293]
Hi,
Great plugin! 
Right now I am using in my search 
```
Organizer::search($request->keywords)
		    ->where('approved', 'true')
		    ->get();
```
This works great, but I was wondering if there was a way to not even index the Organizer models until approved = true? Sorry if this has already been done I tried looking through the other questions but couldn't find anything.

**Comment by babenkoivan** [comment]
Hi @chrisgrim, sorry for the late reply.
Yes, it's possible, have a look here https://laravel.com/docs/6.x/scout#conditionally-searchable-model-instances

**Comment by chrisgrim** [comment]
Amazing @babenkoivan  Thanks so much!!!
