### ISSUE TITLE
Scout Searchable booted only once

### ISSUE THREAD

**Issue by fntneves** [babenkoivan/scout-elasticsearch-driver#296]
Hi,

Following the same question as https://github.com/babenkoivan/scout-elasticsearch-driver/issues/120, I am wondering why it exists.

It is originating failures on test suites, since application is created and destroyed multiple times and the static variable `$isSearchableTraitBooted` remains set to `true`.

Couldn't it be more clever than just stop booting the trait? For instance, do not register observer if it is already registered? IDK, just wondering.

Thank you.

P.S.: I am using version 3.9.1 of this package along with Scout 6.1.3.

**Comment by fntneves** [comment]
I've just realized that there's an open PR for this issue: https://github.com/babenkoivan/scout-elasticsearch-driver/pull/290/files

**Comment by babenkoivan** [comment]
PR is merged, closing
