### ISSUE TITLE
Limit the number of query results

### ISSUE THREAD

**Issue by mace015** [babenkoivan/scout-elasticsearch-driver#300]
***Limit the number of query results***

**Short Description**

Implement a `limit()` method in the `FilterBuilder`.

**Use cases**

Right now I want to limit the results I get from a search to 10 results but I cant do that with `limit()` as I would with an Eloquent builder because `limit()` is not implemented in the `FilterBuilder`.

I've made a hacky workaround for now by using the pagination functionality.

**Comment by RodrigoGalter** [comment]
you can use the **take**

**Comment by mace015** [comment]
> you can use the **take**

Ahh yes, my bad.
