### ISSUE TITLE
Laravel 6.8 : An option with shortcut "s" already exists.

### ISSUE THREAD

**Issue by julienarcin** [babenkoivan/scout-elasticsearch-driver#305]
**Versions**

- scout-elastic-driver: 4.0.1
- laravel/framework: 6.8.0
- php: 7.1.3
- elasticsearch: 7.3.2

**Description**

Laravel 6.8 introduced a new ModelMakeCommand with -s option to generate seed : [ModelMakeCommand.php](https://github.com/laravel/framework/blob/5f278d8367dcec1ff7799e8a18e8a08c570e5972/src/Illuminate/Foundation/Console/ModelMakeCommand.php#L159)

ScoutElasticSearch use -s option to specify search rule for searchable model generation : [SearchableModelMakeCommand.php](https://github.com/babenkoivan/scout-elasticsearch-driver/blob/3d6fb5cc1a002b70da0fa9b4690a2930e8d73590/src/Console/SearchableModelMakeCommand.php#L42-L47)

It conflicts with the new (Laravel 6.8) ModelMakeCommand and generates an application-wide error : 

> An option with shortcut "s" already exists.

**Steps to reproduce**

Update Laravel to 6.8 with ScoutElasticSearch 4.0.1 and it will generate an application-wide error.

**Proposed solution**

Remove -s option to specify search rule (only use --search-rule option).
PR: [307](https://github.com/babenkoivan/scout-elasticsearch-driver/pull/307)

**Comment by orukaz** [comment]
How it can be fixed? Should we make changes in Laravel side, or it is better to make changes on https://github.com/babenkoivan/scout-elasticsearch-driver/blob/3d6fb5cc1a002b70da0fa9b4690a2930e8d73590/src/Console/SearchableModelMakeCommand.php#L42-L47 side? 

The change should be safe, maybe babenkoivan/scout-elasticsearch-driver should overwrite whole getOtions() function or "search-rule" / "s" should be renamed "r" ?

**Comment by julienarcin** [comment]
We shouldn't touch Laravel Core and the parent classes, only subclasses.

The best is to delete the -s option since it's not mandatory (we can always use the --search-rule option). The -r option is also used by Laravel (for resource generation).

I fixed it in the linked PR, waiting for the merge.

**Comment by quaddy** [comment]
I've just encountered the same problem. Thanks for the fix and the PR! I'm looking forward.

**Comment by patriziotomato** [comment]
Same here :-(

**Comment by oixan** [comment]
waiting the fix

**Comment by iget-esoares** [comment]
Issue fixed in v4.0.2.

**Comment by MoogyG** [comment]
Should be possible to report this fix in 3.x branch?

**Comment by MoogyG** [comment]
I suggested #329

**Comment by oixan** [comment]
@MoogyG i fixed by myself  in my 3.x branch. No More update will be released for 3.x so i think its ok.
