### ISSUE TITLE
Compatibility with elasticsearch/elasticsearch 7.1 and laravel/framework 6.10

### ISSUE THREAD

**Issue by cwoodrgr** [babenkoivan/scout-elasticsearch-driver#325]
First of all, thank you for this package, it has worked well.

I am using AWS hosted elasticsearch which currently only allows versions 6.8 or 7.1.

Currently I am running Laravel 6.3 and version 3.12.0 of this package with es 6.8.

I would like to update Laravel to the latest version, however when i do, I get the following error:

"An option with shortcut 's' already exists."

 I started looking at your available versions and found that versions 4.0.1 and 4.0.2 have fixed this error but they also require elasticsearch/elasticsearch 7.3.*, this requirement prevents using either of the es versions allowed by AWS.

Would it be possible to either get an updated version 3 with the error patched or if it wouldn't break this package, change the elasticsearch/elasticserch requirement to ^7.0 on version 4 of this package?

**Comment by babenkoivan** [comment]
Hey, I just released v4.0.3 where I increased available version range for ES client. I hope it will help.

**Comment by cwoodrgr** [comment]
The new version has fixed the issue. Thank you.
