### ISSUE TITLE
Elastic mapping json field even though i did not define it

### ISSUE THREAD

**Issue by tantana5** [babenkoivan/scout-elasticsearch-driver#332]
**Versions**

- scout-elastic-driver: ^4.0
- laravel/framwork: 5.8.*
- php: 7.3.1
- elasticsearch: 7.2.0

**Description**

I have an json field named "data", but i don't want elastic index it. I also did not defined it in "protected $mapping", why did it happen?

"{\"error\":{\"root_cause\":[{\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse field [data.size.net_weight] of type [long] in document with id '480'\"}],\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse field [data.size.net_weight] of type [long] in document with id '480'\",\"caused_by\":{\"type\":\"illegal_argument_exception\",\"reason\":\"For input string: \\\"hard\\\"\"}},\"status\":400}"

**Steps to reproduce**

**Comment by francoism90** [comment]
@tantana5 I had the same issue,. Turns out you need to set `toSearchableArray()` as well: https://laravel.com/docs/6.x/scout#configuring-searchable-data

I'm using this on my model to only include selected fields:
```
    /**
     * @return array
     */
    public function toSearchableArray(): array
    {
        return $this->only(['id', 'name', 'description']);
    }
```

**Comment by tantana5** [comment]
Thanks @francoism90 so much!
I did it!
