### ISSUE TITLE
Ordering by timestamp/ dates

### ISSUE THREAD

**Issue by atmediauk** [babenkoivan/scout-elasticsearch-driver#34]
This was a timestamp issue. Fixed

**Comment by babenkoivan** [comment]
Hey, sorry for the delayed response. I'm quite busy lately. 
I'm glad that you found solution by yourself!

**Comment by atmediauk** [comment]
Thanks :) . This package is absolutely amazing. I'm still getting used to Elastic Search in general but the package works really nicely.
