### ISSUE TITLE
get query result as per type.

### ISSUE THREAD

**Issue by dhavalkaneriya** [babenkoivan/scout-elasticsearch-driver#36]
In elastic search we are importing brand , product , vendor etc.. when we import brand type is brand , for product type is product and for vendor type is vendor.

At last all type of items store on same index in elastic search. For ex: we store uber as a brand and vendor it's store on same index.

when user search uber for brand I only want to get and show uber which type is brand not vendor. How can I do this ?

In model we have **toSearchableArray** function that is below for brand and vendor.

**BrandModel**

```
public function toSearchableArray()
    {
        //$array = $this->toArray();
        return [
            'id' => $this->brand_id,
            'title' => $this->brand_name,
            'img' => $this->image,
            'url' => $this->website,
            'type' => 'brand',
            'location' => [],
            'created_at' => Carbon::now()->toDateTimeString()
        ];
    }
```

**VendorModel**
```
public function toSearchableArray()
    {
        //$array = $this->toArray();
        return [
            'id' => $this->vendor_id,
            'title' => $this->vendor,
            'img' => $this->image,
            'url' => $this->website,
            'type' => 'vendor',
            'location' => [],
            'created_at' => Carbon::now()->toDateTimeString()
        ];
    }
```

when user search he/she select type brand/vendor want to search and as per user input we only want to show related result.

for search we are using below functions.

**for Brand search**
```
Route::get('search/{keyword}', function($keyword) {
        return App\Brand::search($keyword)->paginate(10);
    });
```

**for vendor search**
```
Route::get('search/{keyword}', function($keyword) {
        return App\Vendor::search($keyword)->paginate(10);
    });
```
we have different domains for brand and vendor.

**Comment by babenkoivan** [comment]
Hi @dhavalkaneriya,

Do you store models in the same Elasticsearch type? If so, you try to filter:

```php
App\Brand::search($keyword)->where('type', 'brand')->paginate(10);
```

Note that `type` field must have keyword type in Elasticsearch for strict equality.

**Comment by babenkoivan** [comment]
Close the ticket, because it doesn't look like package issue and there is no further activity from the author.
