### ISSUE TITLE
Another way to do whereIn or whereHas?

### ISSUE THREAD

**Issue by chrisgrim** [babenkoivan/scout-elasticsearch-driver#360]
Hi,
For my project I only want to do a wherebetween for events that have a relationship
```
$events = Event::search(*)->whereHas('shows', function (Builder $query) {
    $query->whereBetween('shows.date', [$request->dates[0],$request->dates[1]]);
})->get();
```
Right now I get the error Method ScoutElastic\Builders\FilterBuilder::whereHas does not exist. I read somewhere else in the questions you were going to add wherein to a later release but I don't think it has been added yet. Do you know if it is close to being added? If not, do you know of a workaround?

**Comment by eqxDev** [comment]
Try put null in the search because then its a SearchBuilder function not a FilterBuilder.

**Comment by chrisgrim** [comment]
I don't actually need to search for a name, I literally just want to filter through my events with Elastic Search. How would I do this?

**Comment by chrisgrim** [comment]
I ended up using the search builder instead of the filter.
