### ISSUE TITLE
Connection issue with elasticsearch 

### ISSUE THREAD

**Issue by oleg-tolkach** [babenkoivan/scout-elasticsearch-driver#368]
CENTOS 7.7
- scout-elastic-driver: v4.2.1
- laravel/framwork: v7.10.3
- php: 7.2.30
- elasticsearch: 7.6.2

php artisan elastic:create-index "App\Scout\ElasticSearch\PostIndexConfigurator"
The promojagers_be__posts index was created!

   Elasticsearch\Common\Exceptions\NoNodesAvailableException

  No alive nodes found in your cluster

  at vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:50
    46|                 return $connection;
    47|             }
    48|         }
    49|
  > 50|         throw new NoNodesAvailableException("No alive nodes found in your cluster");
    51|     }
    52|
    53|     public function scheduleCheck(): void
    54|     {

but when I check elascticsearch indexes by curl 
curl -XGET localhost:9200/_cat/indices
yellow open promojagers_be__posts p5Dz__2gR3qX_K0jTF5O0A 1 1 0 0   283b   283b

then I try to update mapping 
php artisan elastic:update-mapping "App\Models\Post"

   Elasticsearch\Common\Exceptions\Missing404Exception

  {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [promojagers_be__posts_write]","resource.type":"index_or_alias","resource.id":"promojagers_be__posts_write","index_uuid":"_na_","index":"promojagers_be__posts_write"}],"type":"index_not_found_exception","reason":"no such index [promojagers_be__posts_write]","resource.type":"index_or_alias","resource.id":"promojagers_be__posts_write","index_uuid":"_na_","index":"promojagers_be__posts_write"},"status":404}

  at vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:619
    615|             $exception = new AlreadyExpiredException($responseBody, $statusCode);
    616|         } elseif ($statusCode === 403) {
    617|             $exception = new Forbidden403Exception($responseBody, $statusCode);
    618|         } elseif ($statusCode === 404) {
  > 619|             $exception = new Missing404Exception($responseBody, $statusCode);
    620|         } elseif ($statusCode === 409) {
    621|             $exception = new Conflict409Exception($responseBody, $statusCode);
    622|         } elseif ($statusCode === 400 && strpos($responseBody, 'script_lang not supported') !== false) {
    623|             $exception = new ScriptLangNotSupportedException($responseBody. $statusCode);

      +24 vendor frames
  25  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

Please help me to figure out with that ?

**Comment by oleg-tolkach** [comment]
I've commented 
//use Migratable; 
in PostIndexConfigurator and after that i successfully created index 
php artisan elastic:create-index "App\Scout\ElasticSearch\PostIndexConfigurator"
The promojagers_be__posts index was created!

and succesfully updated mapping 
php artisan elastic:update-mapping "App\Models\Post"
The promojagers_be__posts mapping was updated!

but the import command still give me the error 
php artisan scout:import "App\Models\Post"
throw new NoNodesAvailableException("No alive nodes found in your cluster");

seems the commands from current package work good but commands from laravel/scout package is not working 

any ideas ?

**Comment by qingfengbaili** [comment]
I have same issue.

run `curl -XGET localhost:9200/`，get below text.
```json
{
  "name" : "6d2293ae6b23",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "58J5Q0n-QCuLkzkmOjewsw",
  "version" : {
    "number" : "7.4.2",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "2f90bbf7b93631e52bafb59b3b049cb44ec25e96",
    "build_date" : "2019-10-28T20:40:44.881551Z",
    "build_snapshot" : false,
    "lucene_version" : "8.2.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

But when I run `docker-compose exec blog-backend php artisan elastic:create-index "App\Indices\PostIndexConfigurator"`，output error message "No alive nodes found in your cluster".

**Comment by OscarKolsrud** [comment]
> I have same issue.
> 
> run `curl -XGET localhost:9200/`，get below text.
> 
> ```json
> {
>   "name" : "6d2293ae6b23",
>   "cluster_name" : "elasticsearch",
>   "cluster_uuid" : "58J5Q0n-QCuLkzkmOjewsw",
>   "version" : {
>     "number" : "7.4.2",
>     "build_flavor" : "default",
>     "build_type" : "docker",
>     "build_hash" : "2f90bbf7b93631e52bafb59b3b049cb44ec25e96",
>     "build_date" : "2019-10-28T20:40:44.881551Z",
>     "build_snapshot" : false,
>     "lucene_version" : "8.2.0",
>     "minimum_wire_compatibility_version" : "6.8.0",
>     "minimum_index_compatibility_version" : "6.0.0-beta1"
>   },
>   "tagline" : "You Know, for Search"
> }
> ```
> 
> But when I run `docker-compose exec blog-backend php artisan elastic:create-index "App\Indices\PostIndexConfigurator"`，output error message "No alive nodes found in your cluster".

This seems more like a problem with your docker setup. Have you enabled network between the different containers?

**Comment by thyyppa** [comment]
I'm having this problem as well, but I am using AWS ES.

```Domain status Active
Elasticsearch version 7.4
Endpoint https://xxxx.us-west-1.es.amazonaws.com
Domain ARN arn:aws:es:us-west-1:00000:domain/xxxx
Kibana https://xxxx.us-west-1.es.amazonaws.com/_plugin/kibana/
Availability zones 1
Instance type (data) t2.small.elasticsearch
Number of nodes 1
Data nodes storage type EBS
EBS volume type General Purpose (SSD)
EBS volume size 10 GiB
```

The same thing happened last time I tried to set this up and after fiddling with it I think what fixed it was adding 3 "Dedicated Master Nodes". I don't know if that was what for-sure did it, but that's the last thing I did before it started working and I stopped touching it.

After a month I noticed that (of course) AWS was charging me for those additional nodes. I'm only using this for dev so I dropped the cluster and started a new one with a single node. Using the exact same code but with a single node I get the "No alive nodes found in your cluster" error.

Does this have something to do with only using a single node?

(yes, I know I can host ES locally for free, but once deployed I'll be using AWS so it'd be nice to use a single free-tier node for dev)

**Comment by iget-esoares** [comment]
This seems to be a environment related problem, not related to this package itself. Due to this I'm closing the issue (conversation still enabled). Feel free to ask for a reopen if you think this is a bug.

**Comment by oleg-tolkach** [comment]
> This seems to be a environment related problem, not related to this package itself. Due to this I'm closing the issue (conversation still enabled). Feel free to ask for a reopen if you think this is a bug.

Yes it was an issue with curl library  and centos version
