### ISSUE TITLE
update-mapping does not import data from DB

### ISSUE THREAD

**Issue by Firman95** [babenkoivan/scout-elasticsearch-driver#371]
- scout-elastic-driver: ^4.2
- laravel/framwork: 5.8.*
- php: 7.2.30
- elasticsearch: 7.4.2

**Description**

I cannot import data from DB using `php artisan elastic:update-mapping` 

**Steps to reproduce**

- `php artisan make:index-configurator "IndexConfigurator\ListingIndexConfigurator"`. No edit on ListingIndexConfigurator, using default from this package
- `php artisan elastic:create-index "App\IndexConfigurator\ListingIndexConfigurator"`. this works as `http://localhost:9200/_cat/indices` print out `yellow open listing 2MQSrvjFRWacee_Q27MaNw 1 1 0 0 283b 283b`
- this is my `Listing` model 
```
class Listingextends Model
{
    use Searchable;

    /**
     * @var string
     */
    protected $indexConfigurator = ListingIndexConfigurator::class;

    /**
     * @var array
     */
    protected $searchRules = [
        //
    ];

    /**
     * @var array
     */
    protected $mapping = [
        'properties' => [
            'uuid' => [
                'type' => 'text'
            ],
            'address_line_1' => [
                'type' => 'text'
            ],
            'address_line_2' => [
                'type' => 'text'
            ],
        ]
    ];
}
```
- tried `php artisan elastic:update-mapping "App\Models\Listing"` no error but no data imported. I am using `php artisan scout:import "App\Models\Listing"` and its worked, data imported

**Comment by iget-esoares** [comment]
`elastic:update-mapping` will only (as the command name says) update the mappings for an index, but it will not reindex the models. You must manually run `scout:import` if you need.
