### ISSUE TITLE
Data not indexing when using Laravel >=7.0

### ISSUE THREAD

**Issue by oknoote** [babenkoivan/scout-elasticsearch-driver#373]
I have used the scout-elasticsearch-driver successfully in a Laravel 5.8 project which I am now upgrading to Laravel 7. However I see the latest version of this package does not officially support Laravel 7 according to the documentation, but it does support Laravel Scout version 8.

My composer entries look as follows:
"babenkoivan/scout-elasticsearch-driver": "^4.2.1"
"elasticsearch/elasticsearch": "7.3"
"laravel/framework": "^7.0"
"laravel/scout": "^8.0.0"

I'm running PHP 7.3.17 and Elasticsearch 7.3.2.

I can create the indices and update the mappings using the standard artisan elastic:create-index and artisan elastic:update-mapping. Using a simple ES query shows me the indices and mappings are correct. 

However I am unable to import the database entries into the ES indices (see screenshot). The importer appears to run correctly but the indices remain empty.

I have no clue where to look for potential error messages, the storage/logs/laravel.log file doesn't mention anything regarding the laravel-scout-elastic package.

Any help is greatly appreciated, this the final hurdle to migrating the application to Laravel 7! 

P.s. I am running Elasticsearch v7.3.2 and PHP v7.2.3 on Homestead.

![image](https://user-images.githubusercontent.com/1249899/84009697-f2ea5c80-a973-11ea-945e-111657ee6dd1.png)

**Comment by HogenYuan** [comment]
the same question

**Comment by oknoote** [comment]
I just noticed the mentioning of the new Elasticsearch ecosystem at the bottom of the main readme.md. First testresults look promising with data being indexed correctly. @HogenYuan look at the explanation at the bottom of the readme and have a look at the guide on using these packages [here](https://itnext.io/the-ultimate-guide-to-elasticsearch-in-laravel-application-ee636b79419c).
