### ISSUE TITLE
ES 6.0 - Removal of mapping types

### ISSUE THREAD

**Issue by AGNICO** [babenkoivan/scout-elasticsearch-driver#38]
I think there is some problem with mapping types since ES 6.0.: https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html

I wanted to make this set up... Index: Forum, Type 1 (Model): User, Type 2 (Model): Thread. If I follow your tutorial and want to index data with scout import command, I get this error:

```
[Elasticsearch\Common\Exceptions\BadRequest400Exception]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [forum] as the final mappin
g would have more than 1 type: [threads, users]"}],"type":"illegal_argument_exception","reason":"Rejecting mapping update to [forum] as the final mapping would have more than 1 type: [threads, users]"},"status":400}
```

**Comment by babenkoivan** [comment]
Hey, looks like you already know what's the source of the problem. Just create 2 indices, each for one type.

**Comment by AGNICO** [comment]
OK. Sorry for dumb question, I'm new to ES, but can I search across models even if they are not in same index? I mean for example search for all threads created by specific user or search for all users who posted to specific thread? Thanks.

**Comment by babenkoivan** [comment]
You can, but probably not with this package :) Here you can only search by one model. The good news you can add more fields in index model, that model has, using the `toSearchableArray` method. So you can put user information into the thread model.

**Comment by AGNICO** [comment]
OK, I understand now, so this change in ES 6.0 is not a problem at all. Nice package btw. Thanks.
