### ISSUE TITLE
artisan scout:import not working ?

### ISSUE THREAD

**Issue by neoteknic** [babenkoivan/scout-elasticsearch-driver#387]
**Versions**

- scout-elastic-driver: v4.2.3
- laravel/framwork: 7.26.0
- php: 7.4.9
- elasticsearch: 7.8.1

**Description**

Nothing is imported with _artisan scout:import "Model"_

**Steps to reproduce**

All is ok, index creation with artisan elastic:create-index "App\Search\ProductIndexConfigurator" ok
then a scout:import "App\Models\Product"
Lot of imprted messages :
Imported [App\Models\Product] models up to ID: xxxxxx
but nothing imported ! config is ok, index name ok. Tried everything but dont work, no error (scout queue disabled) ...
If I shut down elasticsearch, or delete the index = error, so the index and connection are correct !

**Comment by neoteknic** [comment]
Ok I found is , changed bulk to single, their was an error, fixed, and i'ts ok.
So the bug is : no error with invalid mapping with bulk indexer !

**Comment by Munkhdemberel** [comment]
Hi there! @neoteknic  Can you help me to solve same issue? I am really struggling to solve
same issue. I didn't get your answer. Can you explain step by step procedures for people
who have encountered with same problem.
