### ISSUE TITLE
Error Enabling [_all] is disabled in 6.0 

### ISSUE THREAD

**Issue by khanhvu14** [babenkoivan/scout-elasticsearch-driver#39]
I run command
`php artisan elastic:create-index App\\MyIndexConfigurator`
then catch this error

` [Elasticsearch\Common\Exceptions\BadRequest400Exception]                     
  {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Failed  
   to parse mapping [_default_]: Enabling [_all] is disabled in 6.0. As a rep  
  lacement, you can use [copy_to] on mapping fields to create your own catch   
  all field."}],"type":"mapper_parsing_exception","reason":"Failed to parse m  
  apping [_default_]: Enabling [_all] is disabled in 6.0. As a replacement, y  
  ou can use [copy_to] on mapping fields to create your own catch all field."  
  ,"caused_by":{"type":"illegal_argument_exception","reason":"Enabling [_all]  
   is disabled in 6.0. As a replacement, you can use [copy_to] on mapping fie  
  lds to create your own catch all field."}},"status":400} `

**Comment by khanhvu14** [comment]
I remove default mapping It's OK

**Comment by sdebacker** [comment]
Hello, what about updating the docs ?

**Comment by babenkoivan** [comment]
@sdebacker I will, sorry for confusing

**Comment by babenkoivan** [comment]
Updated the docs, made default mapping deprecated in 3.1.1.

**Comment by johnhaldson** [comment]
Should the default SearchRule class be updated now as well ([buildQueryPayload](https://github.com/babenkoivan/scout-elasticsearch-driver/blob/bcda7431bb0e2e829aa2a9cfc0b3f6fc1c67692d/src/SearchRule.php#L26)) since using `_all` won't work now by default?

**Comment by khanhvu14** [comment]
Yes, right, setting '_all' current is not working override specify field in SearchRule to search anything by field.

**Comment by babenkoivan** [comment]
@johnhaldson thanks for pointing that out, made a fix in 3.1.2 :)
