### ISSUE TITLE
AWS ES instance

### ISSUE THREAD

**Issue by khalifaelbanan** [babenkoivan/scout-elasticsearch-driver#397]
Greetings,
I'm using this package and it works correctly in localhost with my single node ES cluster (with docker). But once I try to use my AWS instance I get an Unauthorized error.
in `scout_elastic.php` I have the following config : 
`'client' => [
        'hosts' => [
            'host' => env('ELASTIC_HOST', 'elastic:9200'),
            'user' => env('ELASTIC_USER'),
            'password' => env('ELASTIC_PASSWORD'),
        ],
    ],`
user and password for basic auth. I'm pretty sure I'm missing some further config
Thanks in advance.

**Comment by mbuk** [comment]
I presume you're using an actual AWS instance not a container?
What is elastic host set to in your env file?
If it's not set the config above will be looking for a host called elastic (which unless you've setup your /etc/hosts file) won't be resolvable.

**Comment by khalifaelbanan** [comment]
Indeed, I'm using an AWS instance and not a container.
In fact I resolved my issue by combining `<user>:<password>@<host>:<port>` and passing it into the `host` parameter.

**Comment by epicsagas** [comment]
@khalifaelbanan This is worked for me, thanks!

Before that, need to config as aws [guide](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-vpc.html#kibana-test)
