### ISSUE TITLE
searchRaw still requires an instance of SearchableModel

### ISSUE THREAD

**Issue by a47ae** [babenkoivan/scout-elasticsearch-driver#4]
The `searchRaw` method on the `ElasticEngine` seems to [still have type hints](https://github.com/babenkoivan/scout-elasticsearch-driver/blob/master/src/ElasticEngine.php#L288) to `SearchableModel`. This breaks the method functionality right now, when using the `Searchable` trait.

**Comment by babenkoivan** [comment]
Thank you for pointing out on a error! I fixed that, now it accepts any eloquent model.
