### ISSUE TITLE
any plans to remove the IndexConfigurator and merge it into models?

### ISSUE THREAD

**Issue by steve3d** [babenkoivan/scout-elasticsearch-driver#40]
as we all know that ES 6.0 and beyond are removing multi-type index, and this will cause every model will need a single index in ES, so if we still need a IndexConfigurator class, and say , we have about 20 models need to be indexed with es, then we will need 20 IndexConfigurator class.

This is some annoying setting, for ES 6.0 and later version.

So I'm wondering if there is a chance to merge the IndexConfigurator class's `getSetting` and `getMapping` function into individual model class?

**Comment by babenkoivan** [comment]
Hey, this is actually a very good question! I was thinking about that, but currently ES6 supports multiple types in one index for migrated instances from ES5. So if I drop it, some of the guys, who uses multiple types and migrated to ES6 will lose some functionality. I will think about making IndexConfigurator deprecated and moving all the configurations to model, but it will take some time.

**Comment by steve3d** [comment]
yes, I know this is the breaking change after all, but the only way to use multi-type in ES6 is by creating the index in ES5. So, you can create to branch, for example , current 3.x will still use the olde IndexConfigurator class, and new 4.x will support ES6.

and by supporting ES6, I think another feature is needed, that is create the index with some prefix. and that is easy.

**Comment by babenkoivan** [comment]
I'd prefer to keep IndexConfigurator, but make it deprecated and get rid of it completely only with ES7 release. I'll try to do that in the next release.

**Comment by ametad** [comment]
The configuration in an own class is good practice imho. Separation of concerns.

**Comment by fzhan** [comment]
@ametad it's good practice, but require bit more tweak to get the decoupling going.
With ES6.2, I now write just as many indexConfigurator as model, as well as mappings. 
And it would be good to consider parent-child join mapping together using Eloquent's relation setup.

**Comment by babenkoivan** [comment]
@fzhan I understand the whole inconvenience of adding configurator for each model, but now we have that separation in ES6, so it makes sense. Also if I rewrite how it works now, we will get not backward compatible version or lots of deprecated stuff, because the changes will be huge. That's why I want to wait for ES7 and get rid of some things entirely.

**Comment by babenkoivan** [comment]
Closing ticket until ES7 is released.
