### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by volkv** [babenkoivan/scout-elasticsearch-driver#404]
Hi. Could you please update composer.json for PHP8 support

**Comment by Hesammousavi** [comment]
yeah we need php 8 support @babenkoivan

**Comment by orukaz** [comment]
Need to check if it is fine to add new version to composer.json or need to upgrade all the depenceies as well:

"require": {
        "php": "^7.1.3**|^8.0**",

**Comment by iget-esoares** [comment]
Hi,

Could you guys please submit a pull request with necessary changes? I think
that PHP8 doesn't introduce any breaking changes to this package, but we
need to check dependencies before rolling up.

**Comment by orukaz** [comment]
> Hi, Could you guys please submit a pull request with necessary changes? I think that PHP8 doesn't introduce any breaking changes to this package, but we need to check dependencies before rolling up.

Hi, I tried to install the package. It gives errors on depedencies. Like I mentioned before, all the versions of dependecies needs to be updated.

Error message:

```sh
 scout-elasticsearch-driver git:(master) composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - elasticsearch/elasticsearch v7.3.0 requires php ^7.1 -> your PHP version (8.0.0) does not satisfy that requirement.
    - elasticsearch/elasticsearch v7.2.2 requires php ^7.1 -> your PHP version (8.0.0) does not satisfy that requirement.
    - elasticsearch/elasticsearch v7.2.1 requires php ^7.1 -> your PHP version (8.0.0) does not satisfy that requirement.
    - elasticsearch/elasticsearch v7.2.0 requires php ^7.1 -> your PHP version (8.0.0) does not satisfy that requirement.
    - elasticsearch/elasticsearch v7.1.1 requires php ^7.1 -> your PHP version (8.0.0) does not satisfy that requirement.
    - elasticsearch/elasticsearch v7.1.0 requires php ^7.1 -> your PHP version (8.0.0) does not satisfy that requirement.
    - elasticsearch/elasticsearch v7.0.2 requires php ^7.1 -> your PHP version (8.0.0) does not satisfy that requirement.
    - elasticsearch/elasticsearch v7.0.1 requires php ^7.1 -> your PHP version (8.0.0) does not satisfy that requirement.
    - elasticsearch/elasticsearch v7.0.0 requires php ^7.1 -> your PHP version (8.0.0) does not satisfy that requirement.
    - Installation request for elasticsearch/elasticsearch >=7.0 <7.4.0 -> satisfiable by elasticsearch/elasticsearch[v7.0.0, v7.0.1, v7.0.2, v7.1.0, v7.1.1, v7.2.0, v7.2.1, v7.2.2, v7.
3.0].
```

**Comment by muthu-kc** [comment]
Please update package to support the latest version of Elasticsearch php package and php v8

**Comment by RolandVerner** [comment]
please make update beecosue in my project everithing:
```
        "babenkoivan/elastic-migrations": "^1.0",
        "babenkoivan/elastic-scout-driver": "^1.0",
        "babenkoivan/elastic-scout-driver-plus": "^1.0",
```

**Comment by babenkoivan** [comment]
Hey @iget-esoares, can you please review open PRs for PHP 8 support and merge one of them?

Sorry guys, I'm more focused now on [the new elastic stack](https://github.com/babenkoivan/scout-elasticsearch-driver#alternatives) 🙂 
I encourage everyone to migrate to the [new driver](https://github.com/babenkoivan/elastic-scout-driver) and [driver plus](https://github.com/babenkoivan/elastic-scout-driver-plus), they both already support PHP 8 😉

**Comment by babenkoivan** [comment]
Hi there 👋🏻

I'm happy to announce, that I've got a spare minute to review few PRs, including PHP 8 support.
They are now merged and released as [v4.3.0](https://github.com/babenkoivan/scout-elasticsearch-driver/releases/tag/v4.3.0) 🎉

PS: I still recommend you to migrate to [the new stack](https://github.com/babenkoivan/scout-elasticsearch-driver#alternatives) 🙂

**Comment by volkv** [comment]
@babenkoivan thanks! 
does your new stack support custom query payloads? like a Search Rules in this package?

**Comment by babenkoivan** [comment]
@volkv yes, you can either use a custom payload:

```php
$searchResult = Book::rawSearch()
    ->query(['match' => ['title' => 'The Book']])
    ->execute();
```

or DSL specific query builders:

```php
$searchResult = Book::matchSearch()
    ->field('title')
    ->query('My book')
    ->execute();
```
