### ISSUE TITLE
Undefined Method When Running Artisan make:searchable-model

### ISSUE THREAD

**Issue by nickpoulos** [babenkoivan/scout-elasticsearch-driver#41]
Not sure why, when following the tutorial in GitHub and in your article on Medium. I am getting the following error:

php artisan make:searchable-model Content --index-configurator=ContentIndexConfigurator

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Illuminate\Foundation\Console\ModelMakeCommand::handle()

I tried artisan cache:clear, artisan config:clear, composer dump-autoload and re-ran, but same result. I also tried to find the SearchableModel class to check that out  ScoutElastic\SearchableModel, but I don't seem to have it. 

Any ideas?

**Comment by nickpoulos** [comment]
Nevermind, in Laravel 5.4 ModelMakeCommand.php does not have handle() function, it has a fire(), which was changed in 5.5. I am going to fork and make a version that works for us in 5.4 if possible. I will make a PR after if you want to check it out.  Thanks.

**Comment by babenkoivan** [comment]
Hey, you can use [v1.3.1](https://github.com/babenkoivan/scout-elasticsearch-driver/tree/v1.3.1). It works with Laravel 5.4. Some new features won't be available, but everything described in the README for that version should work.

**Comment by babenkoivan** [comment]
Close the ticket, because it doesn't look like package issue and there is no further activity from the author.

**Comment by nickpoulos** [comment]
👍

**Comment by babenkoivan** [comment]
@sajadk are you sure, that you are using Laravel 5.6?
`ModelMakeCommand` has the `handle` method https://github.com/laravel/framework/blob/bbe8950cbe86df1818dfe32fed8b906cbf093e5e/src/Illuminate/Foundation/Console/ModelMakeCommand.php#L37

**Comment by sajadk** [comment]
@babenkoivan oh..sorry! I was running this command in Laravel 5.4 version of the project.
