### ISSUE TITLE
Not an issue more of a question

### ISSUE THREAD

**Issue by mbuk** [babenkoivan/scout-elasticsearch-driver#42]
Hi love the package and just assessing if I can use it in my latest project.

I can see how the app\model search and searchRaw will work for me; but I have a very specific use case where we have (an almost global) search.  

Think forum posts
Blog posts 
News articles
Etc

I might be missing something obvious here but is there a way with this package to search all the different types in a given index. My understanding at the moment is that the model effectively is the type.

So say I wanted to search for “London” across all blog posts and all news and all forum posts.

Any pointers appreciated.

**Comment by babenkoivan** [comment]
Hi @mbuk 

Your understanding is absolutely correct, currently model = type, in the future model = index (in ES7). So for your purpose it probably won't work. I can think up some work around, but it's better to use [ES client](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/index.html) directly in your case.

**Comment by mbuk** [comment]
Cheers @babenkoivan 
Thinking I might go a hybrid - the mapping’s etc from your package are super convenient and all excect maybe two searches are restricted to a given model.

I’ll have a play around. Thanks again.

**Comment by babenkoivan** [comment]
Close the ticket, because there is no further activity from the author.
