### ISSUE TITLE
Is there any way to use souce filtering to select only the required fields?

### ISSUE THREAD

**Issue by frozenex** [babenkoivan/scout-elasticsearch-driver#44]
Say i have the following object
`
{
        "id": 609,
        "group_id": null,
        "tag": "Animals",
        "count": 22,
        "is_featured": 0,
        "created_by": 4,
        "updated_by": 4,
        "created_at": "2017-03-09 08:28:54",
        "updated_at": "2017-03-19 20:03:03",
        "deleted_at": null
}
`

What to do if i only want 
`
{
        "id": 609,
        "tag": "Animals",
        "count": 22,
}
`

**Comment by babenkoivan** [comment]
Hey, take a look on `toSearchableArray` method in `Searchable` trait.

**Comment by frozenex** [comment]
Am already using the toSearchableArray() method to only index the required fields. However when i perform the search am getting all the other fields.

```
    public function toSearchableArray() {
        return array_only($this->toArray(), [ 'id', 'tag', 'count' ]);
    }
```

**Comment by babenkoivan** [comment]
Check also the mapping for your index. I think that you might need to recreate index.

**Comment by babenkoivan** [comment]
Close the ticket, because it doesn't look like package issue and there is no further activity from the author.
