### ISSUE TITLE
How implement query sections outside of query=>bool?

### ISSUE THREAD

**Issue by Visionary89** [babenkoivan/scout-elasticsearch-driver#5]
For example how I can get highlight section?
There is solution to get non eloquent fields?

**Comment by babenkoivan** [comment]
The search method returns collection of models, there is no place for meta data like highlighting. You can use the [`searchRaw`](https://github.com/babenkoivan/scout-elasticsearch-driver#usage) method to specify any additional parameters you want. But keep in mind, that it returns raw data from ES.
