### ISSUE TITLE
Offset needed. Page size and from methods in ES

### ISSUE THREAD

**Issue by atoropin** [babenkoivan/scout-elasticsearch-driver#51]
There is a need to send "size" and "from" parameters to Elastic.

For example:
->page(10, 20) //10 results starting from 20

Or:
->perpage(10)->offset(20)

**Comment by babenkoivan** [comment]
Hey @atoropin, I released a new version with new method `from`. Now you can set offset and limit:

```
App\MyModel::search('phone')
    // set offset
    ->from(0)
    // set limit
    ->take(10);
```
And of course, you can use pagination:

```
App\MyModel::search('phone')
    // set page limit, page name, page number
    ->paginate(10, 'page', 2)
```
