### ISSUE TITLE
Some guidance not an issue - geopoints

### ISSUE THREAD

**Issue by mbuk** [babenkoivan/scout-elasticsearch-driver#52]
Hi there,
Thanks for creating such a useful package.

Hope you don't mind, but seeking a bit of guidance with geopoints and want to check I'm doing it right.

I've created a mapping: 
with 
`          
           'location' => [
                'type' => 'geo_point'
            ],
            

`
and I was going to use `toSearchableArray()` something like this:

`
public function toSearchableArray()
    {
        $array = $this->toArray();
        $array['location'] = $array['lat'].','.$array['lng'];
        return $array;
    }
`

Is this sensible or is there a better way that I'm missing?

**Comment by babenkoivan** [comment]
Hi @mbuk, sorry for the late reply.

I think you have to index geo points as associative array, i.e.:

```
$array['location'] = [
    'lat': $array['lat'],
    'lon': $array['lng']
];
```

**Comment by mbuk** [comment]
@babenkoivan works like a charm - I did something like this
```
  public function toSearchableArray()
    {
             $array = $this->toArray();
             $array['location'] = $array['lat'].','.$array['lng'];
             unset($array['lat']);
             unset($array['lng']);
             return $array;
    }
```
