### ISSUE TITLE
call elastic commands in code

### ISSUE THREAD

**Issue by maralbe** [babenkoivan/scout-elasticsearch-driver#53]
hi @babenkoivan 
I want to create some commands using laravel commands.. and when I call it like this : 

`Artisan::call('php artisan elastic:create-index <configurator class>')`

I get error that  There are no commands defined in the "php artisan elastic" namespace ...

how to resolve it?
thank you

**Comment by Jimmea** [comment]
You have call wrong it.. U can call like :
 Artisan::call( 'elastic:create-index', [...options]);

**Comment by maralbe** [comment]
thanks for your reply..
I edit my command like you said, but the error is still there.. I think the problem is from ` 'elastic:create-index' ` that doesn't recognize the `elastic:`
I don't know how to fix it

**Comment by maralbe** [comment]
I was in wrong way... 
I fixed my issue..
thanks
