### ISSUE TITLE
Is it possible to return aggregations along with hits using your package?

### ISSUE THREAD

**Issue by mmccaff** [babenkoivan/scout-elasticsearch-driver#55]
Hi @babenkoivan -

I am interested in using aggregations in addition to query results, to see how the results are bucketed.

Let's say I have a query like this, that returns aggregations in addition to hits.

```
curl -H 'Content-Type: application/json' -XPOST 'http://localhost:9200/content/content/_search?pretty' -d '{
	"query":{
		"bool":{
			"must":[{
				"multi_match":{
					"query":"cats",
					"fields":["title","desc"]}}
					]}
		},
		"sort":[{"published_at":"desc"},{"_score":"desc"}],
         "aggs" : {
   	          "sources" : {
   	              "terms" : { "field" : "sub_source" }
   	          }
   	      }
		}'
```

Is there a way, using your package, that I could get the aggregations in addition to the documents returned in the hits?

If not, do you have any thoughts on the direction to contribute that ability to your package? For example, I might want one call on the built query which returns the aggregations, and another which returns the collection of models.  

(or would this fall within the realm of being a Scout request?)

Thanks!

UPDATE: I just noticed this PR. Perhaps it allows this? 
https://github.com/babenkoivan/scout-elasticsearch-driver/pull/47

**Comment by robtesch** [comment]
I currently acheive this by using the searchRaw method. The results do of course come in raw format, but i've found this is no problem for my need. Example:

`Agent::searchRaw([
            'from' => 0,
            'size' => 50000,
            'query' => [
                'bool' => [
                    'filter' => [
                        ['term' => ['company_id' => $company->id]],
                    ],
                ],
            ],
			'aggs' => [
				'average_initial_ttr' => [
					'avg' => ['field' => 'init_agent_reply_time'],
				],
			],
        ]);`

**Comment by mmccaff** [comment]
Thanks, this works and is what we ended up doing. At the time, I didn't realize that searchRaw returned the raw response from Elastic.

I will close this.

**Comment by terrasoff** [comment]
There is no way to build aggregation queries so far. I think @babenkoivan may put this important notice to the description or to the roadmap.
