### ISSUE TITLE
support for Laravel 5.6 and Scout 4.0

### ISSUE THREAD

**Issue by robtesch** [babenkoivan/scout-elasticsearch-driver#56]
Hi, just wondering if/when you will be supporting Scout 4.0 which was released alongside Laravel 5.6.

At the moment it seems everything is working by putting the following line in composer require:

"laravel/scout": "4.0.1 as 3.0.9"

But it would of course be better not to need to do that.

**Comment by babenkoivan** [comment]
Hi @robtesch, I'll try it this weekend, if everything will be fine and back compatible, I'll release a new version.

**Comment by babenkoivan** [comment]
New version v3.3.0 is released, if you notice any bugs with new Scout or Laravel, don't hesitate to open a new issue with error description.
