### ISSUE TITLE
Error: Class 'Config' not found (ScoutElasticServiceProvider)

### ISSUE THREAD

**Issue by lasmanis** [babenkoivan/scout-elasticsearch-driver#57]
Hi Ivan,

first of all thank you for your great work!!!!!

I've been using your package for the last week now with absolutely no issues except one!

I'm getting an error that the Config class is not defined in the ServiceProvider (line 62).

Fixable by either updating the use statement (`use Illuminate\Support\Facades\Config;`) or by switching from using the Config Facade to the config helper function.

Do you confirm the issue?

I'd be happy to send you a PR if you'd like.

**Comment by babenkoivan** [comment]
Hi @lasmanis, apparently you don't have alias in `config/app.php`:
```
'Config' => Illuminate\Support\Facades\Config::class
```  
But anyways, I added a full facade name to the service provider, to avoid this issue in the future.
