### ISSUE TITLE
Connecting to AWS Elasticsearch Service

### ISSUE THREAD

**Issue by patrickomeara** [babenkoivan/scout-elasticsearch-driver#59]
well done @babenkoivan a great package

I've posted in elastic/elasticsearch-php#646 do you have any ideas on this?

**Comment by babenkoivan** [comment]
Hi @patrickomeara, did you configure port for the client? Is it `443` (as far as I understood you are using `https`)?

**Comment by JustSteveKing** [comment]
I can confirm you just need to add `443` onto the host as I had the same issue

**Comment by patrickomeara** [comment]
yep, the port is needed
