### ISSUE TITLE
How i can check index is exists?

### ISSUE THREAD

**Issue by Visionary89** [babenkoivan/scout-elasticsearch-driver#6]
I want check something like `->hasIndex($indexName)` on IndexConfigurator
There is solution?

**Comment by babenkoivan** [comment]
Hi @Visionary89,

The IndexConfigurator entity serves only for index configuration, but you can use the ElasticClient facade to check if an index exists. Like below:

```
use ScoutElastic\Facades\ElasticClient;

ElasticClient::indices()->exists(['index' => $indexName]);
```
