### ISSUE TITLE
Implementation of Fuzzy

### ISSUE THREAD

**Issue by evinkuraga** [babenkoivan/scout-elasticsearch-driver#63]
Solid package. It does however seem to lack the fuzzy search option unless utilizing a raw query.

If using a raw query, the results are returned as an ElasticSearch object, which would mean it would need to be converted into a collection afterwards to use. Perhaps add a method to convert it back to the proper collection? 

If there is already an easy way to use the fuzzysearch, it should probably be included in the readme. Adding it as a Search Rule also seems to break the system.

**Comment by babenkoivan** [comment]
Hi @evinkuraga, you can create a search rule, like following:

```
class MySearchRule extends SearchRule
{
    public function buildQueryPayload()
    {
        return [
            'must' => [
                'fuzzy' => [
                    'my_field' => $this->builder->query
                ]
            ]
        ];
    }
}
```

**Comment by Delindel** [comment]
Hey @babenkoivan is there a way to set a fuzzy search for all the mapped elements of a model?

**Comment by babenkoivan** [comment]
@Delindel you can try something like this:

```
class MySearchRule extends SearchRule
{
    public function buildQueryPayload()
    {
        return [
            'must' => [
                'multi_match' => [
                    'query' => $this->builder->query,
                    'fuzziness' => 'auto'
                ]
            ]
        ];
    }
}
```

**Comment by Delindel** [comment]
Thanks! Ill give it a try in a bit!

Amazing package man, ES works better than TNTsearch for 30M+ records.

**Comment by JapSeyz** [comment]
Sorry to bring up an old issue.

Is there a way to set the fuzzy search as the default method in the IndexConfigurator settings array?

**Comment by Delindel** [comment]
Hey man! I ended up doing search rules for every model and define fuzzyness there, honestly fuzzy on everything is madness for the engine.

**Comment by babenkoivan** [comment]
Hey @JapSeyz and @Delindel, you can create one search rule with fuzziness and use it in multiple models. Of course, if you have different logic per model it's better to create one rule per model.

**Comment by babenkoivan** [comment]
Closed due to inactivity.

**Comment by poncianodiego** [comment]
I have I'm trying to perform a fuzzy search over a text field but my app returns no results when I set up the search rule:

`Product::search("text query")->rule(FuzzyMatchRule::class)->get()`

FuzzyMatchRule.php:

```
    public function buildQueryPayload()
    {
        return [
            'must' => [
                'fuzzy' => [
                    'name' => $this->builder->query
                ]
            ]
        ];
    }
```
Product.php:

```
 protected $mapping = [
        "properties" => [ 
            "name" => [
                "type" => "text"
            ],
            "category" => [
                "type" => "text"
            ],
            "sku" => [
                "type" => "keyword"
            ],
            "specs" => [
                "type" => "object"
            ],
            "brand" => [
                "type" => "text"
            ],
...
    public function toSearchableArray(){

        $searchableArray = $this->toArray();

        unset($searchableArray['created_at']);
        unset($searchableArray['updated_at']);

        $searchableArray['category'] = $this->category->name;

        return $searchableArray;
    }

```

**Comment by poncianodiego** [comment]
What I want is simply to be able to search for example the query string: "PROT" so that it returns the products containing that string in the name field, for example in within my data it should return product with name: "02-0690-00_THROAT PROTECTOR"

**Comment by babenkoivan** [comment]
@poncianodiego have you solved the issue? Your search rule looks correct. Did you try to search the whole word `PROTECTOR` or use default search rule?
