### ISSUE TITLE
Index with eloquent relationship

### ISSUE THREAD

**Issue by fzhan** [babenkoivan/scout-elasticsearch-driver#66]
Would it be possible to:
1. Map an index with property type = nested
2. Index relationship under Eloquent to allow 
2.a search a,b under relationship of a->b
2.b search a,b under relationship of a->c->b

Currently the mapping is done with property set to nested, but with scount:import the index doesn't contain value from relationship.

**Comment by fzhan** [comment]
@Jimmea do you meant this function? https://github.com/laravel/scout/blob/4.0/src/Searchable.php#L115

I will give it a go, thanks!

**Comment by Jimmea** [comment]
Yes. U can override that function on your model.

**Comment by babenkoivan** [comment]
Is the issue solved? Can I close it? :)

**Comment by fzhan** [comment]
@babenkoivan I've switch to Neo4j for relationship searching with edges, this was simply the wrong application for elasticsearch.
