### ISSUE TITLE
Selective columns

### ISSUE THREAD

**Issue by Alexwijn** [babenkoivan/scout-elasticsearch-driver#67]
Any chance support can be added to only select certain columns when mapping the result to eloquent models when paginating?

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Builder.php#L683
The above link refers to the `paginate` method on the Eloquent Builder, it supports `columns` and defaults to `*`. I like to have the same behavior. Thanks!

**Comment by StefanoGroenland** [comment]
We need this!

**Comment by babenkoivan** [comment]
Hi guys, I can't change the interface of paginate method, because I inherit it from scout package. But I added new method `select` for the builder, now you can specify columns, that you want to get from ES and database:

```php
App\MyModel::search('phone')
    ->select(['title', 'price'])
    ->get();
```

Should work for both: `get` and `paginate`.

**Comment by Alexwijn** [comment]
Thanks for the update! Unfortunately this will cause issues when the elasticsearch index has different columns than the eloquent model. This will result in `Column not found` errors.

**Comment by babenkoivan** [comment]
Hey @Alexwijn, you shouldn't select fields, that are not in the database. The error will appear only if you request fields that are not in your model. So consider this method as `select model fields`.

**Comment by Alexwijn** [comment]
Yeah, I understand that. What I mean is that if you do not specify any fields it chooses the fields that are in ElasticSearch and that results in `Column not found` errors.

**Comment by babenkoivan** [comment]
This is not an issue anymore :D since v3.4.1, if you don't specify selected fields it will grab all columns.

**Comment by Alexwijn** [comment]
Oeps...sorry. I did not saw that version.
