### ISSUE TITLE
Method count not support ???

### ISSUE THREAD

**Issue by Jimmea** [babenkoivan/scout-elasticsearch-driver#68]
Sometime. i want to show total user visit my website in today, week, month and some condition with where. ??? I have not see any method support on package ??? . 

I have fork a branch add_count_to_filterbuilder ...

**Comment by babenkoivan** [comment]
Hey @Jimmea, I've added method `count` in the new release `v3.4.0`. Now you can use it like this:

```php
App\MyModel::search('phone') 
    ->count();
```

**Comment by Jimmea** [comment]
Thank u :))
