### ISSUE TITLE
Pass Curl params to ES client?

### ISSUE THREAD

**Issue by jorgenb** [babenkoivan/scout-elasticsearch-driver#7]
Hey,

Great work @babenkoivan ! Finally a promising Scout driver for Elasticsearch.

I need to send additional CURL parameters to the PHP-ES client. E.g:

```
 'client' => [
        'curl' => [
            CURLOPT_HTTPHEADER => [
                'Authorization: Bearer ' . env('API_KEY', '')
            ]
        ]
    ],
```

Is there an easy way to do this with your implementation?

All the best,
  J

**Comment by babenkoivan** [comment]
Hi @jorgenb!

If you want to use basic authentication, the easiest way to do that is to specify your credentials in the host parameter, like this:

```
'client' => [
        'hosts' => [
            'http://user:pass@localhost:9200'
        ]
 ]
```

**Comment by jorgenb** [comment]
@babenkoivan, thanks for responding.

I am not using basic auth. I need to be able to pass parameters to the underlying CURL transport for the PHP-ES client. Specifically the HTTP `Authorization` header.

Here is some sample code that is working:

```
    $hosts = [
        'localhost:8080'
    ];

    $client = ClientBuilder::create()
        ->setHosts($hosts)
        ->build();

    $params = [
    'client' => [
      'curl' => [
            CURLOPT_HTTPHEADER => [
            'Authorization: Bearer '.env('API_KEY', ''),
                ],
        ],
    ],
        'index' => 'index',
        'type'  => 'type',
        ...
];

    $response = $client->search($params);
```
This is is not a well documented feature of the PHP client, but there is some information here:

https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_per_request_configuration.html#_providing_custom_query_parameters

Were in your code do you build the client?

**Comment by babenkoivan** [comment]
Sorry for misunderstanding you. The driver takes the `client` option from the config/scout_elastic.php file and passes it to the `ClientBuilder::fromConfig`. So you can try to configure curl in the config file, like following:

```
return [
    'client' => [
        'hosts' => [
            env('SCOUT_ELASTIC_HOST', 'localhost:9200')
        ],
        'connectionParams' => [
            'client' => [
                'curl' => [
                    CURLOPT_HTTPHEADER => [
                        'Authorization: Bearer '.env('API_KEY', ''),
                    ]
                ]
            ]
        ]
    ],
    'update_mapping' => env('SCOUT_ELASTIC_UPDATE_MAPPING', true)
];
```

**Comment by jorgenb** [comment]
Thanks.

**Comment by daylaborers** [comment]
Maybe, the better was is following the ES Doku:
```
'client' => [
        'hosts' => [
            [
                'host'   => env('SCOUT_ELASTIC_HOST', 'localhost'),
                'port'   => env('SCOUT_ELASTIC_PORT', '9200'),
                'scheme' =>  env('SCOUT_ELASTIC_SCHEME', 'https'),
                'user'   =>  env('SCOUT_ELASTIC_USER', 'user'),
                'pass'   =>  env('SCOUT_ELASTIC_PASS', 'pass'),
            ]
        ]
    ],
```
