### ISSUE TITLE
Issue introduced by v3.4.0, selecting unexistent columns

### ISSUE THREAD

**Issue by iget-master** [babenkoivan/scout-elasticsearch-driver#70]
Hi,

I've just ran `composer update` and loaded v3.4.0. But a serious issue occurred:

Some of my model's `toSearchableArray()` (most of them) in many applications outputs fields that doesn't exists on the database context, only on ElasticSearch context.

Didn't read the code changes yet, but looks like the new version is using the `toSearchableArray()` to define the columns to select on query.

The problem, as said, is that some coluns only exists on ElasticSearch context, so the Database Query will fail with

    SQLSTATE[42S22]: Column not found: 1054 Unknown column 'someColumnName' in 'field list'

Instead of guessing the columns, it should keep the default Eloquent selects (that defaults to `[*]`).

For now, rolling back to v3.3.* solves the issue.

**Comment by babenkoivan** [comment]
Hi @iget-master, thank you for your quick feedback!
Unfortunately, I forgot about the possibility to put additional (not database) data to ES. 
I'll try to think up a solution to the issue or will remove `select` feature from the package by tomorrow.

**Comment by babenkoivan** [comment]
Hey, I released new v3.4.1. 
Can you confirm, that you don't have the issue anymore?

**Comment by iget-master** [comment]
I'll confirm tonight, okay?

**Comment by iget-master** [comment]
Hi @babenkoivan. I can confirm that v3.4.1 fixed the issue. Closing for now! Thanks!
