### ISSUE TITLE
Issue with Bulk Index

### ISSUE THREAD

**Issue by vikram0460** [babenkoivan/scout-elasticsearch-driver#72]
I have try to index the existing records it is giving an Method Illuminate\Database\Eloquent\Collection::create does not exist.

I have used like this
APP\MyModel::get()->create();

I have configured 'indexer' => env('SCOUT_ELASTIC_INDEXER', 'bulk') and 
chunk to 'chunk' => [
        'searchable' => 10000000000,
        'unsearchable' => 500,
    ]
And also one more question can we set chunk to unlimited, because I have more records to search from?

**Comment by babenkoivan** [comment]
Hi @vikram0460 and sorry for the late reply. 

Have you solved the issue?
When you call `get` on your model, you deal with DB (Eloquent ORM), not ES (Scout).

**Comment by vikram0460** [comment]
@babenkoivan I have tried previously, it didn't work. As I was in the early stages, switched to different plug-in. You can close the issue. Thanks
