### ISSUE TITLE
Update and create a document are necessary on scout-elasticsearch-driver ??? 

### ISSUE THREAD

**Issue by Jimmea** [babenkoivan/scout-elasticsearch-driver#73]

**Comment by babenkoivan** [comment]
Hi @Jimmea, I don't understand your question, can you provide me with more details?

**Comment by Jimmea** [comment]
@babenkoivan  At the moment. When user create new post. i want to that post tobe index to elasticsearch and also update that post. ??

**Comment by babenkoivan** [comment]
The post should be reindexed automatically at the creation and update.

**Comment by Jimmea** [comment]
We can't not each user create a post and reindex all record. At here i only want to index new post.

**Comment by babenkoivan** [comment]
@Jimmea but why you need to reindex all of them, only new post will be indexed.

**Comment by babenkoivan** [comment]
Closed due to inactivity.
