### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by mikefrancis** [babenkoivan/scout-elasticsearch-driver#74]
Hi there,

I really want to use this package but our infra is stuck on PHP 7.0 at the moment.

I was wondering if it would be possible to let me know what areas of the codebase are PHP 7.1+ so that I can fork this package and make it work for our need.

Or maybe Travis could be used to run your test suite in a PHP 7.0 container if the coverage is good to do it for us?

Any thoughts would be greatly appreciated. Thanks!

**Comment by babenkoivan** [comment]
Hi @mikefrancis, 

I think it should be compatible with php 7.0. 
Neither of dependencies require 7.1+ and in my own code I haven't used any new 7.1 features yet.
I required 7.1+ to keep the same version as new Laravel requirement and be able to add such things as type hinting, when I refactor the code.

You can try to install the package ignoring environment requirements:
```
composer require --ignore-platform-reqs babenkoivan/scout-elasticsearch-driver
``` 

Or you can use `v3.2.1` for php 7.0.

**Comment by mikefrancis** [comment]
Awesome, thank you
