### ISSUE TITLE
Driver [elasticsearch] not supported.

### ISSUE THREAD

**Issue by SirBrooks** [babenkoivan/scout-elasticsearch-driver#75]
Hello,
I tryed to get the scout-elasticsearch-driver working but had this problem:

After installation and configuration I get this error:
"InvalidArgumentException  : Driver [elasticsearch] not supported."

I use PHP 7.2.2 and laravel 5.6 and elasticsearch 6.
babenkoivan/scout-elasticsearch-driver v3.4.1

at /home/.../vendor/laravel/framework/src/Illuminate/Support/Manager.php: 97
     93|             if (method_exists($this, $method)) {
     94|                 return $this->$method();
     95|             }
     96|         }
  >  97|         throw new InvalidArgumentException("Driver [$driver] not supported.");
     98|     }
     99| 
    100|     /**
    101|      * Call a custom driver creator.

  Exception trace:

  1   Illuminate\Support\Manager::createDriver("elasticsearch")
      /home/.../vendor/laravel/framework/src/Illuminate/Support/Manager.php : 69

  2   Illuminate\Support\Manager::driver("elasticsearch")
      /home/.../vendor/laravel/scout/src/EngineManager.php : 21

Thank you for helping.

**Comment by babenkoivan** [comment]
Hi @SirBrooks, did you set driver in the `config/scout.php` to `elastic`? I looks like you're trying to use another driver `elasticsearch`.

**Comment by SirBrooks** [comment]
Yes, this was my first thought ... and I did this mistake at first.
But I changed it and I get the same error again ...

**Comment by babenkoivan** [comment]
Do you get the same error with `elasticsearch` driver? Did you try to clear cache? My driver is called `elastic`, the error you get isn't related to the package.

**Comment by Surt** [comment]
artisan cache:clear?

**Comment by khanhvu14** [comment]
try php artisan config:clear?

**Comment by SirBrooks** [comment]
yes it was something with the cache.
I removed and reinstalled the package with composer.
Cleared the cache.
Now it is running fine.

Thank you!
