### ISSUE TITLE
Feature request: Support setting `refresh` parameter

### ISSUE THREAD

**Issue by iget-master** [babenkoivan/scout-elasticsearch-driver#77]
The refresh parameter on Elasticsearch indexing (and querying) as [well documented](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-refresh.html) allows three values:

- `true`
- `false`
- `wait_for`

The last one is my focus here, but the other two are important too.

# The use case

Imagine some integration testings, where we insert some record on database, and try to query it almost immediately after, due the conception of Elasticsearch, it's probable that the test fail, since the indexing is **near**-real time.

Providing a way to globally set the `refresh=wait_for` on elasticsearch's requests, or at least on insertions, avoids this issue.

# How to archive

That's the point, didn't studied the code yet, but I think that isn't so hard.

**Comment by babenkoivan** [comment]
Good idea @iget-master. I think it would be helpful to have a global default config and per model configuration.

**Comment by babenkoivan** [comment]
Hey @iget-master, I added a new option to the configuration file in `v3.5.0` - `document_refresh`, check the docs! Notice that it should have a string value or null (not used at all).

**Comment by yashiroiori** [comment]
As you can do so that document_refresh can be put null before starting a queue that uses a model, for example in a bulk load, the problem is that it is very slow if you use document_refresh as wait_for.
