### ISSUE TITLE
Use highlight

### ISSUE THREAD

**Issue by faycal1** [babenkoivan/scout-elasticsearch-driver#78]
Hi Baben , I find your Code very Usefull , Thnk you for that,

I was Searching How to use [highlight](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-request-highlighting.html#search-request-highlighting) to the search result bu no succes , is there a way ?

Thank you

**Comment by babenkoivan** [comment]
Currently there is no solution, you can only achieve that with `searchRaw` method, but it returns `raw` results.

**Comment by iget-master** [comment]
That's a nice feature that I did not know! Would be great if this package features this!

**Comment by babenkoivan** [comment]
Hi guys, I released new version 3.6.0 with highlight support.
To use it, just describe new method `buildHighlightPayload` in your search rules as shown in README.
If you will have any questions or problems regarding new functionality, feel free to reopen the issue, but for now I close it.
