### ISSUE TITLE
HTTPS ES host

### ISSUE THREAD

**Issue by zajinx** [babenkoivan/scout-elasticsearch-driver#80]
Hello,
Can you please help me understand how i need to configure scout_elastic.php in order to connect to a HTTPS ES host, for example https://elasticsearch?

error message when trying to create a new index using SCOUT_ELASTIC_HOST=elasticsearch:443
`
php artisan elastic:create-index App\\NewIndexConfigurator

In StaticNoPingConnectionPool.php line 51:
                                        
  No alive nodes found in your cluster  
                   
`

**Comment by babenkoivan** [comment]
Hi @zajinx,
Try `https://elasticsearch:9200`. For more options, have a look at [client documentation](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_configuration.html).

**Comment by babenkoivan** [comment]
Closed due to inactivity.

**Comment by bavial** [comment]
Hello, I have the same problem. I try localhost:9200, https://elasticsearch:9200, elasticsearch:9200 But the error remained
 curl -XGET localhost:9200 Command in my server Successfully Displays ES Server Information
What am I doing wrong? Snks

**Comment by bavial** [comment]
> Hello, I have the same problem. I try localhost:9200, https://elasticsearch:9200, elasticsearch:9200 But the error remained
> curl -XGET localhost:9200 Command in my server Successfully Displays ES Server Information
> What am I doing wrong? Snks

Found the cause of the error. In the elasticsearch.yml file, you must specify the VM address of the VM in the network (ex 192.168.10.10), and not the localhost or 127.0.0.1.
