### ISSUE TITLE
Two Elasticsearch infrastructures on one project

### ISSUE THREAD

**Issue by anoukhermsen** [babenkoivan/scout-elasticsearch-driver#81]
Hi,

I have a local Elasticsearch where I want to write documents to, and an online Elasticsearch where I want to get documents from.

I have been searching, and still am, for a while on how to, read and write from and to, two different Elasticsearch’s in one app. if so, how can I achieve this?

Thanks in advance.

**Comment by babenkoivan** [comment]
Hi @anoukhermsen, this is complicated. Only some workarounds come to my mind. I'm using `ElasticClient` [facade](https://github.com/babenkoivan/scout-elasticsearch-driver/blob/master/src/Facades/ElasticClient.php), that is basically [Elasticsearch PHP Client](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/index.html). You can make 2 configurations: host to read and host to write and switch host every time you try to read or write, using `setHosts` method of the client. To achieve that you can use model observer.

**Comment by anoukhermsen** [comment]
Thank you for your answers, I will try to develop it on monday and I will tell you if it works.

Have a nice weekend

**Comment by anoukhermsen** [comment]
I've tried to work with ElasticClient facade but we figured out that our "read from" host Elasticsearch version 2.4.6 is, so we have to see if another package has what we want and otherwise we have to make something else. :disappointed_relieved:

Thanks for your help!
