### ISSUE TITLE
ElasticSearch on the pivote table data

### ISSUE THREAD

**Issue by SabrineClarck** [babenkoivan/scout-elasticsearch-driver#82]
Hello, I would like first to thank you for this awesome package, it was very helpful.

I have an issue, regarding the indexing mechanism , I have a relationship many to many and I have the pivot table containing data, the data is what I'm searching upon, it works fine when I use the command : `php artisan scout:import name_of_model` 
I get to search on the data that I have in the DB, but when I add or update this model the index doesn't update until I execute the same command .
Please guide me on this, I don't know where the problem is,

Best regards

**Comment by babenkoivan** [comment]
Hi @SabrineClarck,
Check please if you are using a queue broker for indexing.
If so, check if the consumers are running.

**Comment by SabrineClarck** [comment]
Hi @babenkoivan , Thank you for your quick reply,
No I'm not using any queue for indexing, here below the code I'm using: 
-config/scout.php-
`<?php

return [

    'driver' => env('SCOUT_DRIVER', 'elastic'),

    'prefix' => env('SCOUT_PREFIX', ''),

    'queue' => env('SCOUT_QUEUE', false),

    'chunk' => [
        'searchable' => 1000,
        'unsearchable' => 1000,
    ],

    'soft_delete' => false,

];`
-config/scout_elastic.php-
`<?php

return [
    'client' => [
        'hosts' => [
            env('SCOUT_ELASTIC_HOST', 'localhost:9200')
        ]
    ],
    'update_mapping' => env('SCOUT_ELASTIC_UPDATE_MAPPING', true),
    'indexer' => env('SCOUT_ELASTIC_INDEXER', 'single'),
    'document_refresh' => env('SCOUT_ELASTIC_DOCUMENT_REFRESH')
];`
-App/DocumentIndexConfigurator.php-
`namespace App;

use ScoutElastic\IndexConfigurator;
use ScoutElastic\Migratable;

class DocumentIndexConfigurator extends IndexConfigurator
{
    use Migratable;

    /**
     * @var array
     */
    protected $settings = [
        //
    ];
}`
And my Model -Document.php-
`class Document extends Model
{
    use Searchable;
    use SoftDeletes;
protected $indexConfigurator = DocumentIndexConfigurator::class;
    
    public $table = 'documents';
    public $timestamps = true;

    protected $searchRules = [];
protected $mapping = ['properties' => [
        'id' => [
            'type' => 'integer',
        ],
        ]
    ];
public function fields()
    {
        return $this->belongsToMany('App\Models\Field')->withPivot('data')->withTimestamps();
    }
public function toSearchableArray()
    {
        $this->fields;
        return $this->toArray();

    }`

for the documents records, they are first saved without fields (pivot -data-), then the user can update the document (model) with the fields he need providing a data that is stored in the pivot table,
could be the problem that the document(model) doesn't get updated when the fields is added ?? 

it only works after I use the scout import commande ,

Thank you for your time, I appreciated

**Comment by babenkoivan** [comment]
If I understood you correctly, users update related models and it doesn't trigger parent model update.
To achieve that you can create model observer for related model and call `searchable`/`unsearchable` method on the parent model, when `save`/`delete` child model.

**Comment by SabrineClarck** [comment]
The trick was to call `searchable` after eager loading the relationship in question, an example 

```php


    /**
     * Update a document field
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Document $document
     * @param \App\Models\Field $field
     * @return \Illuminate\Http\Resources\Json\Resource
     */
    public function updateField(Request $request, Document $document, Field $field)
    {

        $value = json_encode(['value' => $request->input('data')]);
        $document->fields()
            ->updateExistingPivot($field->id,
                ['data' => $value]
            );
        $document->fields();

        // update the index to have the latest changes of the documents
        $document->searchable();

        return $this->show($document->id);
    }

```

Thank you again for your time and this helpful package, I'm closing the issue
