### ISSUE TITLE
Support scroll in search query

### ISSUE THREAD

**Issue by airycanon** [babenkoivan/scout-elasticsearch-driver#83]
Hi, thank you for the great work.

I have a issue that I need scroll api in search query, here is [official document](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html)
Currently I have to use the elasticsearch client to do this:
```php
$client = ClientBuilder::create()->build();
$params = [
    "scroll" => "30s",          
    "size" => 50,             
    "index" => "my_index",
    "body" => [
        "query" => ...
    ]
];
$response = $client->search($params);
```

Could you please support scroll in this package? Thanks for any help.

**Comment by babenkoivan** [comment]
Hi @airycanon, I'm thinking about new version and I'll consider implementing this feature in it.
For now, you can use [`searchRaw`](https://github.com/babenkoivan/scout-elasticsearch-driver#usage) method for scroll search.

**Comment by airycanon** [comment]
@babenkoivan `searchRaw` is ok, thanks for your nice work.

**Comment by rmshah989** [comment]
@babenkoivan do you know by when you would be working on the new version

**Comment by jgcbrouns** [comment]
I cant see how to add scroll/scan parameter to searchRaw? It only expects 1 parameter which is an array of query, while the scroll parameter is put directly in the request URL.
