### ISSUE TITLE
User first_name, last_name auto-complete facility - looking for correct mapping / settings

### ISSUE THREAD

**Issue by TheBigK** [babenkoivan/scout-elasticsearch-driver#85]
First of all, @babenkoivan - thank you for saving 100+ hours and frustration. Can't thank you enough!

I'm trying to achieve `@mention` facility to suggest users. I've user's `first_name`, `last_name` and `name` field, which is a combination of the `first_name` and `last_name`. So far, I've been able to get all my data indexed. 

Here's how my current settings look like -

	protected $settings = [
		'analysis'  => [
			'filter'    =>  [
				'autocomplete_filter'   =>  [
					'type'  =>  'edge_ngram',
					'min_gram'  =>  2,
					'max_gram'  =>  12,
				],
			],
			'analyzer'  =>  [
				'autocomplete' =>  [
					'type'  =>  'custom',
					'tokenizer' =>  'standard',
					'filter'    =>  ['lowercase', 'autocomplete_filter']
				]
			]
		]
	];

and 

    public function buildQueryPayload()
    {
	    return [
		    'must'  =>  [
			    'multi_match'   =>  [
				    'query'     => $this->builder->query,
				    'fields'    => ['first_name', 'last_name', 'name^2'],
				    'type'      =>  'phrase_prefix'
			    ]
		    ]
	    ];
    }

This is my best try so far; but I'm not happy with the results. I've the following in my User model -

	public function toSearchableArray() {
		return [
			'first_name'    =>  $this->first_name,
			'last_name'     =>  $this->last_name,
			'name'          =>  $this->first_name . ' ' . $this->last_name
		];
	}

I'm thinking of adding an extra field from my database to the index called `last_activity_at` and then sort the suggested users according to those who've the most recent last_activity. 

Can someone suggest if I need to make changes to my filter, analyzer or the query? The end result I want to achieve is -

User types: `@Joh` . The system should return

1. 'John Doe'  [most recently active]
2. 'John Doe' [second most recently active]
3. 'Johan Kent' 
4. 'Johar Woe' 

... like that. If the `last_activity_at` field is null, ES should only match based upon the closest search. 

Would really appreciate your suggestions. Have spent over 3 days on trying to understand but at this time, I need a helping hand. 

Thank you again for this wonderful driver!

**Comment by babenkoivan** [comment]
Hi @TheBigK,

First of all, I think you have to use [edge ngram tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-edgengram-tokenizer.html), instead of filter. 

Second, you probably don't need anything except just `name` field in your index, if you expect users to mention like `first name` + `last name`.

Third, instead of `phrase_prefix` you can use just `match` query, because edge ngram splits string to tokens in prefix manner.

All said above is just my thoughts and needed to be checked :)

**Comment by TheBigK** [comment]
@babenkoivan - Thanks a lot for your reply. I've been experimenting and have been able to achieve the desired result. 

Now, the only thing I want to know if there's a way to specify the 'sort' field at the time of building the search query like this -

    public function buildQueryPayload()
    {
	    return [
		    'must'  =>  [
			    'match' =>  [
			    	'name'  =>  $this->builder->query,
			    ]
		    ],
		    'sort'  =>  [
			    'last_activity_at'  =>  [
				    'order' =>  'desc'
			    ]
		    ]
	    ];
    }

If I specify the 'last_activity_at' field like `$users = User::search($request->s)->orderBy('last_activity_at', 'desc')->get();`, then does the sorting happen at ES level or is handled by Laravel?

**Comment by babenkoivan** [comment]
The correct way to sort is to use `orderBy` method.
It's used inside ES, not Eloquent.

**Comment by TheBigK** [comment]
You, sir, are officially being declared 'awesome'.

**Comment by babenkoivan** [comment]
Closed due to inactivity.

**Comment by TheBigK** [comment]
I'd like to know that too. Would really appreciate if @babenkoivan could provide with an example.

**Comment by babenkoivan** [comment]
Hi guys, currently it's not possible to use suggest API.

**Comment by TheBigK** [comment]
@babenkoivan - is there any possibility of using multi-index search? I think ES supports it.

**Comment by babenkoivan** [comment]
ES supports it of course, but not Scout.

**Comment by Naveedali1234** [comment]
@TheBigK I am also trying to achieve the same functionality which you want, but i am not sure where to use the `$settings` variable and `buildQueryPayload`, your help will be really appreciated.

waiting for your kind response.

thank you
