### ISSUE TITLE
search over multiple models

### ISSUE THREAD

**Issue by MeeDNite** [babenkoivan/scout-elasticsearch-driver#87]
Hi,
Is there any way to search over multiple models with one request?
I tried to create a single site-wide index. but when Importing rows to ES, models will get overwritten by duplication of Primary Key.
Any Ideas?

**Comment by babenkoivan** [comment]
Hi @MeeDNite,
There is no such possibility at the moment.

**Comment by babenkoivan** [comment]
Closed due to inactivity.
