### ISSUE TITLE
Capability to create aliases

### ISSUE THREAD

**Issue by manojnegii90** [babenkoivan/scout-elasticsearch-driver#9]
Is this package has the ability to create aliases ? we need it for zero downtime ?

**Comment by babenkoivan** [comment]
Hi @manojnegii90, right now it can't create aliases. But I can add this feature in the next release.

**Comment by manojnegii90** [comment]
HI,

Thanks for your reply. When can I expect the next release?

**Comment by babenkoivan** [comment]
I will try to add this feature till Monday.

**Comment by babenkoivan** [comment]
Sorry for still not implementing the necessary commands. I'll try to add them this week.

**Comment by babenkoivan** [comment]
Hi @manojnegii90, I tried to make built in zero down time mechanism, but it's very tricky and I'm afraid it won't work for everyone. So I ended up with thought that if developers need it on their project, they can make it by themselves according to their needs.

As for your first question, you can create alias by using the `ElasticClient` facade as following:

```php
use ScoutElastic\Facades\ElasticClient;

ElasticClient::indices()->putAlias([
    'index' => 'your_index_name',
    'name' => 'your_alias'
]);
```

**Comment by manojnegii90** [comment]
Thanks brother. I appreciate your efforts. It will be of great help.
