### ISSUE TITLE
Docs: Remind to add Provider into app.php

### ISSUE THREAD

**Issue by NicksonYap** [babenkoivan/scout-elasticsearch-driver#97]
Add this to README, sorry too lazy for fork and pull request :P
```
    'providers' => [

         ...


        //Elasticsearch with Laravel Scout
        Laravel\Scout\ScoutServiceProvider::class,
        ScoutElastic\ScoutElasticServiceProvider::class,
    ],
```

Has to be done before 
```
php artisan vendor:publish --provider="Laravel\Scout\ScoutServiceProvider"
php artisan vendor:publish --provider="ScoutElastic\ScoutElasticServiceProvider"
```

**Comment by NicksonYap** [comment]
Also good to note that an IndexConfigurator has to be created for each Model

> Indices created in Elasticsearch 6.0.0 or later may only contain a single mapping type. Indices created in 5.x with multiple mapping types will continue to function as before in Elasticsearch 6.x. Mapping types will be completely removed in Elasticsearch 7.0.0.

https://www.elastic.co/guide/en/elasticsearch/reference/6.x/removal-of-types.html

**Comment by NicksonYap** [comment]
PR: https://github.com/babenkoivan/scout-elasticsearch-driver/pull/99

**Comment by babenkoivan** [comment]
Hi @NicksonYap,
Thanks for your contribution!
I think we can close the issue and continue discussion in the MR itself.
What do you think?

**Comment by babenkoivan** [comment]
Hi @NicksonYap,
Thanks for your contribution!
I think we can close the issue and continue discussion in the MR itself.
What do you think?
